"use client";
import {useEffect,useState} from "react";
export default function EstimatorAdministration(){
  const [data,setData]=useState<any>(null);const [selected,setSelected]=useState<any>(null);const [config,setConfig]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const [costInput,setCostInput]=useState("");const [reviewNotes,setReviewNotes]=useState("");const [review,setReview]=useState<any>(null);const [confirmed,setConfirmed]=useState(false);
  const [exception,setException]=useState("strategic-value");const [reason,setReason]=useState("");const [evidence,setEvidence]=useState("");const [providerId,setProviderId]=useState("");const [status,setStatus]=useState("");
  const control={display:"block",width:"100%",maxWidth:"100%",minHeight:44,fontSize:16,color:"#17201b",background:"#fff",padding:12,boxSizing:"border-box" as const};
  async function load(){const response=await fetch("/api/admin/p5-estimators");const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);setConfig(JSON.stringify(body.configuration,null,2));}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function save(){setBusy(true);setError("");try{const response=await fetch("/api/admin/p5-estimators",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:data.version,configuration:JSON.parse(config)})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}}
  async function inspect(id:string){const response=await fetch(`/api/admin/p5-estimators?id=${id}`);const body=await response.json();if(!response.ok)throw new Error(body.error);setSelected(body);setReview(null);setConfirmed(false);setStatus("");
    const e=body.estimate.internal_estimate;const prior=body.reviews?.find((r:any)=>r.source_revision===body.estimate.revision);const service=body.estimate.payload.answers.service;
    const input=prior?.input||{service,revision:"assigned-by-server",scopeSummary:e?.scope?.text||body.estimate.payload.text||"",lines:e?.lines||[],coverage:e?.coverage||["materials","field-labor","owner-production","subcontractors","permits-inspections","engineering-design","equipment-rentals","disposal","travel-mobilization","protection-cleanup","project-supervision","closeout","other-direct"].map(category=>({category,status:"missing",reason:""})),risks:e?.riskFactors||[],assumptions:e?.assumptions||[],exclusions:e?.exclusions||[],missingInformation:e?.missingInformation||[],allowances:e?.allowances||[],uncertainty:"high",locationProvided:Boolean(body.estimate.payload.answers.location||body.estimate.payload.answers.address),manualAdjustments:[]};
    setCostInput(JSON.stringify(input,null,2));setReviewNotes(prior?.notes||"");setReason("");setEvidence("");setProviderId("");
  }
  async function action(body:any){setBusy(true);setError("");setStatus("");try{const response=await fetch("/api/admin/p5-estimators",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"The action could not be completed.");return result;}catch(e){setError(e instanceof Error?e.message:"Review failed");return null;}finally{setBusy(false);}}
  async function reviewCosts(){try{const result=await action({action:"save-review",id:selected.estimate.id,expectedRevision:selected.estimate.revision,input:JSON.parse(costInput),notes:reviewNotes});if(result){setReview(result);setConfirmed(false);setStatus("Saved this cost review. Changed scope, costs or financial policy require a new review and approvals.");}}catch(e){setError(e instanceof Error?e.message:"Invalid cost data");}}
  async function publish(){const result=await action({action:"publish-review",reviewId:review?.reviewId,confirmed});if(result){await inspect(selected.estimate.id);await load();setStatus(`Published revision ${result.revision}. ${result.crmNeedsReview?"Update the existing CRM record and reconcile it below.":"Deliveries are queued; check their status below."}`);}}
  return <main style={{maxWidth:1100,margin:"0 auto",padding:"36px 20px",overflowWrap:"anywhere"}}><h1>P5 estimator administration</h1>{error&&<p role="alert">{error}</p>}{data&&<>
    <h2>Overhead and pricing review</h2><p>Official planning overhead: $420,000 annually. Enter the conservative revenue forecast and its source. Saving records a quarterly review; it does not convert the $2.4 million sales goal into a forecast.</p>
    <p>Current company allocation: {(data.allocation.total*100).toFixed(2)}%. {data.allocation.warnings.map((w:any)=>w.message).join(" ")}</p>
    <details><summary>Review financial configuration and cost books</summary><label htmlFor="p5-admin-config">Financial forecast, current cost evidence, quantity rules and scope coverage</label><textarea id="p5-admin-config" value={config} onChange={e=>setConfig(e.target.value)} rows={22} style={{display:"block",width:"100%",maxWidth:"100%",fontSize:16,fontFamily:"monospace",color:"#17201b",background:"#fff",padding:14}}/><button onClick={save} disabled={busy} style={{minHeight:44,padding:12}}>Save reviewed configuration</button></details>
    <h2>Delivery health</h2><ul>{data.delivery.map((d:any)=><li key={d.status}>{d.status}: {d.count}</li>)}</ul><button style={{minHeight:44,padding:12}} onClick={async()=>{setBusy(true);try{const r=await fetch("/api/admin/p5-estimators",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"process-delivery"})});if(!r.ok)throw new Error((await r.json()).error);await load();}catch(e){setError(String(e));}finally{setBusy(false);}}} disabled={busy}>Process due deliveries</button>
    <h2>Saved projects and partial estimates</h2><ul>{data.drafts.map((d:any)=><li key={d.id} style={{padding:"14px 0",borderBottom:"1px solid #888"}}><button style={{minHeight:44,textAlign:"left"}} onClick={()=>inspect(d.id).catch(e=>setError(e.message))}>{d.contact?.name||"Partial project"} | {d.service||"Service not selected"} | {d.status}</button><p>{d.contact?.email||"Contact not yet supplied"}</p></li>)}</ul>
    {selected&&<section><h2>Estimate record</h2><p><a href={`/api/admin/p5-estimators?id=${selected.estimate.id}&pdf=administrative`}>Administrative PDF</a>{selected.estimate.customer_estimate&&<> | <a href={`/api/admin/p5-estimators?id=${selected.estimate.id}&pdf=customer`}>Customer PDF</a></>}</p><ul>{selected.uploads.map((f:any)=><li key={f.id}><a href={`/api/admin/p5-estimators/upload?id=${f.id}`}>{f.name}</a></li>)}</ul>
      <h2>Review and publish project costs</h2><p>Review every uploaded file and scope detail. Itemize current direct costs, quantities, evidence, labor burdens, landed material costs, allowance inclusions and selection deadlines. Record why each remaining cost category does not apply. The server applies overhead, contingency and the service profit policy.</p>
      <fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}>
        <label htmlFor="p5-review-costs">Itemized project costs and assumptions (JSON)</label><textarea id="p5-review-costs" rows={24} style={{...control,fontFamily:"monospace"}} value={costInput} onChange={e=>{setCostInput(e.target.value);setReview(null);setConfirmed(false);}}/>
        <label htmlFor="p5-review-notes">Scope, upload, risk and warning review notes</label><textarea id="p5-review-notes" rows={4} style={control} value={reviewNotes} onChange={e=>{setReviewNotes(e.target.value);setReview(null);setConfirmed(false);}}/>
        <button style={{minHeight:44,padding:12}} onClick={reviewCosts}>Save and calculate reviewed costs</button>
        {review&&<><h3>Reviewed financial result</h3><p>Contract planning amount: {review.estimate.contractPrice.toLocaleString("en-US",{style:"currency",currency:"USD"})}. Operating profit: {(review.estimate.targetOperatingProfit*100).toFixed(2)}%. Divisor: {review.estimate.divisor}.</p>
          <ul>{review.estimate.warnings.map((w:any,i:number)=><li key={i}><strong>{w.severity==="block"?"Must resolve":"Review"}:</strong> {w.message}</li>)}</ul>
          {review.estimate.warnings.some((w:any)=>w.code==="owner-approval-required")&&<><h3>Owner exception approval</h3><p>Nick and Jared must each sign in with their own configured account and approve this saved revision. Any change invalidates these approvals.</p><label htmlFor="p5-exception">Exception basis</label><select id="p5-exception" style={control} value={exception} onChange={e=>setException(e.target.value)}>{["strategic-value","low-risk","repeatable-scope","supplier-pricing","pipeline-benefit"].map(v=><option key={v} value={v}>{v.replaceAll("-"," ")}</option>)}</select><label htmlFor="p5-owner-reason">Written evidence for the exception</label><textarea id="p5-owner-reason" style={control} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/><button style={{minHeight:44,padding:12}} onClick={async()=>{const result=await action({action:"approve-review",reviewId:review.reviewId,exception,reason});if(result)setReview(result);}}>Record my owner approval</button></>}
          <label style={{display:"flex",gap:12,padding:"18px 0"}}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I verified the scope, uploads, current cost evidence, allowances, exclusions, quantities, risk and warning dispositions. Send this preliminary result to the customer and administrators.</span></label>
          <button style={{minHeight:44,padding:12}} disabled={!review.estimate.publishable||!confirmed} onClick={publish}>Publish reviewed planning result</button>
        </>}
        {selected.deliveries.some((d:any)=>d.status==="needs-review")&&<><h3>Reconcile uncertain delivery</h3><p>Check the provider before retrying. For an existing CRM lead, update that record with the saved revision and confirm its identifier. Never create another lead to resolve an uncertain acknowledgement.</p><label htmlFor="p5-delivery-evidence">Provider lookup and outcome evidence</label><textarea id="p5-delivery-evidence" style={control} rows={3} value={evidence} onChange={e=>setEvidence(e.target.value)}/><label htmlFor="p5-provider-id">Confirmed message or CRM record identifier</label><input id="p5-provider-id" style={control} value={providerId} onChange={e=>setProviderId(e.target.value)}/>{selected.deliveries.filter((d:any)=>d.status==="needs-review").map((d:any)=><div key={d.id} style={{padding:"12px 0"}}><p>{d.destination}: {d.last_error}</p>{([['confirmed-sent','Confirm delivered or CRM updated'],['confirmed-not-sent','Confirmed absent; queue delivery']] as const).map(([decision,label])=><button key={decision} style={{minHeight:44,padding:12}} onClick={async()=>{const result=await action({action:"reconcile-delivery",deliveryId:d.id,decision,evidence,providerId});if(result){await inspect(selected.estimate.id);await load();setStatus("Reconciliation recorded.");}}}>{label}</button>)}</div>)}</>}
      </fieldset><details><summary>Complete saved record, revisions and delivery audit</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",maxWidth:"100%",fontSize:13}}>{JSON.stringify(selected,null,2)}</pre></details></section>}
    {status&&<p role="status">{status}</p>}
  </>}</main>;
}
