"use client";
import {useEffect,useState} from "react";
export default function EstimatorAdministration(){
  const [data,setData]=useState<any>(null);const [selected,setSelected]=useState<any>(null);const [config,setConfig]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function load(){const response=await fetch("/api/admin/p5-estimators");const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);setConfig(JSON.stringify(body.configuration,null,2));}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function save(){setBusy(true);setError("");try{const response=await fetch("/api/admin/p5-estimators",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:data.version,configuration:JSON.parse(config)})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}}
  async function inspect(id:string){const response=await fetch(`/api/admin/p5-estimators?id=${id}`);const body=await response.json();if(!response.ok)throw new Error(body.error);setSelected(body);}
  return <main style={{maxWidth:1100,margin:"0 auto",padding:"36px 20px",overflowWrap:"anywhere"}}><h1>P5 estimator administration</h1>{error&&<p role="alert">{error}</p>}{data&&<>
    <h2>Overhead and pricing review</h2><p>Official planning overhead: $420,000 annually. Enter the conservative revenue forecast and its source. Saving records a quarterly review; it does not convert the $2.4 million sales goal into a forecast.</p>
    <p>Current company allocation: {(data.allocation.total*100).toFixed(2)}%. {data.allocation.warnings.map((w:any)=>w.message).join(" ")}</p>
    <details><summary>Review financial configuration and cost books</summary><label htmlFor="p5-admin-config">Financial forecast, current cost evidence, quantity rules and scope coverage</label><textarea id="p5-admin-config" value={config} onChange={e=>setConfig(e.target.value)} rows={22} style={{display:"block",width:"100%",maxWidth:"100%",fontSize:16,fontFamily:"monospace",color:"#17201b",background:"#fff",padding:14}}/><button onClick={save} disabled={busy} style={{minHeight:44,padding:12}}>Save reviewed configuration</button></details>
    <h2>Delivery health</h2><ul>{data.delivery.map((d:any)=><li key={d.status}>{d.status}: {d.count}</li>)}</ul><button style={{minHeight:44,padding:12}} onClick={async()=>{setBusy(true);try{const r=await fetch("/api/admin/p5-estimators",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"process-delivery"})});if(!r.ok)throw new Error((await r.json()).error);await load();}catch(e){setError(String(e));}finally{setBusy(false);}}} disabled={busy}>Process due deliveries</button>
    <h2>Saved projects and partial estimates</h2><ul>{data.drafts.map((d:any)=><li key={d.id} style={{padding:"14px 0",borderBottom:"1px solid #888"}}><button style={{minHeight:44,textAlign:"left"}} onClick={()=>inspect(d.id).catch(e=>setError(e.message))}>{d.contact?.name||"Partial project"} | {d.service||"Service not selected"} | {d.status}</button><p>{d.contact?.email||"Contact not yet supplied"}</p></li>)}</ul>
    {selected&&<section><h2>Estimate record</h2><p><a href={`/api/admin/p5-estimators?id=${selected.estimate.id}&pdf=administrative`}>Administrative PDF</a> | <a href={`/api/admin/p5-estimators?id=${selected.estimate.id}&pdf=customer`}>Customer PDF</a></p><ul>{selected.uploads.map((f:any)=><li key={f.id}><a href={`/api/admin/p5-estimators/upload?id=${f.id}`}>{f.name}</a></li>)}</ul><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",maxWidth:"100%",fontSize:13}}>{JSON.stringify(selected,null,2)}</pre></section>}
  </>}</main>;
}
