// @ts-nocheck
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {dynamicScopeFields,questionContext,scopeFieldApplies,scopePromptApplies} from '../lib/p5/dynamicQuestions.ts';
import {scopeQuestions,finishOptionsForService} from '../lib/p5/adaptive.ts';
import {instructionPrompts} from '../lib/p5/clarifications.ts';
const extraction=(extra={})=>({summary:'',facts:[],conflicts:[],missingInformation:[],reviewNotes:[],...extra});
const instructions=(extra={})=>({inclusions:[],exclusions:[],responsibilities:[],buildings:[],floors:[],questions:[],separateBuildings:false,laborOnly:false,materialsOnly:false,...extra});
const takeoff=(component,quantity,unit='SF',extra={})=>({id:component,component,description:component,quantity,unit,basis:'stated',evidence:'Explicit test scope measurement',sources:[{source:'QA.pdf',page:1,sheet:'A1',revision:''}],supersedes:[],issues:[],building:'',floor:'',...extra});
const build=(extra={})=>({service:'new-construction',taskList:'Complete new home construction',sqft:'2400',garageIncluded:'no',finish:'mid-range',...extra});
const fields=(a,x=null,cost=[],text='')=>dynamicScopeFields(a,x,cost,text);
test('unknown service asks only project type',()=>assert.deepEqual(fields({}),['service']));
test('a complete basic build has no repeated questions',()=>assert.deepEqual(fields(build()),[]));
test('a build asks finish only when missing and unselected',()=>assert.deepEqual(fields(build({finish:''})),['finish']));
test('actual finish specifications suppress the generic tier question',()=>assert.deepEqual(fields(build({finish:'',materials:'Quartz counters, stock cabinets and LVP'})),[]));
test('source-backed material specifications also suppress the tier',()=>assert.deepEqual(fields(build({finish:''}),extraction({facts:[{field:'materials',value:'Quartz counters and stock cabinets',basis:'stated',source:'spec.pdf',evidence:'Schedule',confidence:.95}]}),['finish']),[]));
test('only trim in a whole-build plan does not ask whole-home area or finish',()=>{
 const a={service:'new-construction',taskList:'Trim only',estimatingInstructions:'Price only baseboard trim',trimLf:'200'};
 assert.deepEqual(fields(a,extraction({instructions:instructions({inclusions:['Baseboard trim only']}),takeoffs:[takeoff('plumbing fixtures',15,'EA')]}),['sqft','finish','garageIncluded','cabinetBaseLf','plumbing']),[]);
});
test('typed trim-only scope works before structured extraction',()=>assert.deepEqual(fields({service:'new-construction',taskList:'Price only trim',trimLf:'200'},null,['sqft','garageIncluded','finish']),[]));
test('missing trim length asks that measurement, not full-house questions',()=>assert.deepEqual(fields({service:'new-construction',taskList:'Price only trim'},null,['sqft','finish','trimLf']),['trimLf']));
test('full source takeoff replaces a redundant trim measurement',()=>assert.deepEqual(fields({service:'new-construction',taskList:'Price only trim'},extraction({takeoffs:[takeoff('baseboard trim',200,'LF')]}),['trimLf']),[]));
test('a second unmeasured trim row preserves the quantity question',()=>assert.deepEqual(fields({service:'handyman',taskList:'Install baseboard trim'},extraction({takeoffs:[takeoff('baseboard trim bedroom',120,'LF'),takeoff('baseboard trim hall',null,'LF',{basis:'uncertain'})]})),['trimLf']));
test('uncertain photographic quantities are not accepted as measurements',()=>assert.ok(fields({service:'handyman',taskList:'Install baseboard trim'},extraction({takeoffs:[takeoff('trim',null,'LF',{basis:'uncertain'})]})).includes('trimLf')));
test('a takeoff with unresolved issues does not suppress a question',()=>assert.ok(fields({service:'handyman',taskList:'Install trim'},extraction({takeoffs:[takeoff('trim',200,'LF',{issues:['Conflicting length']})]})).includes('trimLf')));
test('units are never interchangeable',()=>assert.ok(fields({service:'handyman',taskList:'Install trim'},extraction({takeoffs:[takeoff('trim',200,'SF')]})).includes('trimLf')));
test('excluded plumbing is not revived by a document clarification',()=>assert.deepEqual(fields({service:'handyman',taskList:'Replace two doors',exclusions:'Plumbing'},extraction({clarifications:[{field:'plumbing',question:'Which fixtures?',reason:'scope'}]}),['plumbing']),[]));
test('negated flooring in a repair list does not create flooring questions',()=>assert.deepEqual(fields({service:'handyman',taskList:'Replace two doors; do not replace flooring'}),[]));
test('first floor is a location, not a flooring task',()=>assert.deepEqual(fields({service:'handyman',taskList:'Replace two doors on the first floor'}),[]));
test('a floor plan is a document, not a flooring task',()=>assert.deepEqual(fields({service:'handyman',taskList:'Install two doors per floor plan'}),[]));
test('a faucet replacement is not area-based demolition',()=>assert.deepEqual(fields({service:'handyman',taskList:'Remove and replace one faucet'}),[]));
test('actual floor demolition retains its missing measurement',()=>assert.ok(fields({service:'handyman',taskList:'Demolition of flooring'}).includes('demolitionSqft')));
test('a one-vanity cabinet job does not ask upper/tall cabinet lengths',()=>assert.deepEqual(fields({service:'cabinet-product',taskList:'Supply one bathroom vanity',cabinetBaseLf:'3',finish:'mid-range'}),[]));
test('new upper-only cabinets do not imply new base cabinets',()=>assert.deepEqual(fields({service:'cabinet-product',taskList:'Supply upper cabinets for kitchen',cabinetUpperLf:'10',finish:'mid-range'}),[]));
test('tall units are asked when actually requested',()=>assert.deepEqual(fields({service:'cabinet-product',taskList:'Supply tall cabinets for pantry',finish:'mid-range'}),['cabinetTallLf']));
test('an explicit zero is a valid answer, not a missing measurement',()=>assert.deepEqual(fields({service:'cabinet-product',taskList:'Supply tall cabinets for pantry',cabinetTallLf:'0',finish:'mid-range'}),[]));
test('cabinet hardware repairs do not request cabinet runs',()=>assert.deepEqual(fields({service:'handyman',taskList:'Install pulls on existing cabinets'}),[]));
test('modular cabinet counts in plans can be priced without invented linear feet',()=>assert.deepEqual(fields({service:'cabinet-product',taskList:'Supply base cabinets for kitchen',finish:'mid-range'},extraction({takeoffs:[takeoff('base cabinets',6,'EA')]})),[]));
test('owner-supplied material is not an exclusion of its labor',()=>assert.ok(fields({service:'handyman',taskList:'Install LVP flooring',exclusions:'Flooring material purchase only'}).includes('flooringSqft')));
test('labor-only work does not ask global material tier',()=>assert.deepEqual(fields(build({finish:'',estimatingInstructions:'Labor only'}),extraction({instructions:instructions({laborOnly:true})})),[]));
test('known no-garage answer prevents a garage-area question',()=>assert.deepEqual(fields(build(),null,['garageSqft']),[]));
test('an included garage gets its missing area question',()=>assert.deepEqual(fields(build({garageIncluded:'yes'})),['garageSqft']));
test('ordinary bedroom addition does not require a garage decision',()=>assert.deepEqual(fields({service:'addition',sqft:'300',taskList:'Build one bedroom addition',finish:'mid-range'},null,['garageIncluded','garageSqft']),[]));
test('small repairs do not ask homeowners to estimate contractor labor hours',()=>assert.deepEqual(fields({service:'handyman',taskList:'Repair a fence gate'},null,['laborHours']),[]));
test('an explicit hourly scope can ask hours',()=>assert.deepEqual(fields({service:'handyman',taskList:'Hourly time and materials handyman work'},null,['laborHours']),['laborHours']));
test('a specific missing specification follows the extracted question',()=>assert.deepEqual(fields({service:'handyman',taskList:'Replace a water heater'},extraction({clarifications:[{field:'plumbing',question:'What tank size is required?',reason:'Price depends on capacity'}]})),['plumbing']));
test('stale cabinet dependencies disappear after service and scope change',()=>assert.deepEqual(fields({service:'handyman',taskList:'Replace two doors'},null,['cabinetBaseLf','cabinetUpperLf','cabinetTallLf','finish']),[]));
test('a specified kitchen faucet job is not a complete kitchen renovation',()=>assert.deepEqual(fields({service:'kitchen',taskList:'Full faucet replacement only; retain all cabinetry'}),[]));
test('answered extracted facts are not asked twice',()=>assert.deepEqual(fields({service:'handyman',taskList:'Install baseboard trim'},extraction({facts:[{field:'trimLf',value:'200',source:'scope.pdf',evidence:'200 LF baseboard',confidence:.98,basis:'stated'}]})),[]));
test('low confidence facts remain questions',()=>assert.deepEqual(fields({service:'handyman',taskList:'Install baseboard trim'},extraction({facts:[{field:'trimLf',value:'200',source:'scope.pdf',evidence:'Blurred text',confidence:.5,basis:'stated'}]})),['trimLf']));
test('a source conflict does not falsely count as answered',()=>assert.deepEqual(fields({service:'handyman',taskList:'Install trim'},extraction({facts:[{field:'trimLf',value:'200',source:'scope.pdf',evidence:'200 LF',confidence:.99,basis:'stated'}],conflicts:[{field:'trimLf',values:['200','300'],explanation:'Different revisions'}]})),['trimLf']));
test('unrelated specialist questions are rejected for explicit trim-only work',()=>{const c=questionContext({service:'new-construction',estimatingInstructions:'Price only trim',taskList:'Install trim'});assert.equal(scopePromptApplies('plumbing','What plumbing fixtures?',c),false);assert.equal(scopePromptApplies(undefined,'Which electrical panel is required?',c),false);assert.equal(scopePromptApplies('trimLf','How much trim?',c),true);});
test('unknown specialist decisions are retained, not silently resolved',()=>assert.equal(scopePromptApplies(undefined,'Which engineering detail applies?',questionContext(build())),true));
test('scope-aware filtering preserves a real multi-trade question',()=>assert.equal(scopePromptApplies(undefined,'Does the trim include electrical chase access?',questionContext({service:'new-construction',taskList:'Price trim only'})),true));
test('no exact property address is required for a preliminary price',()=>assert.equal(scopeFieldApplies('address',questionContext(build())),false));
test('repeated dependencies produce only one question',()=>assert.deepEqual(fields({service:'handyman',taskList:'Install trim'},null,['trimLf','trimLf']),['trimLf']));
test('selected building excludes quantities from an unrequested building',()=>{const x=extraction({instructions:instructions({buildings:['House']}),takeoffs:[takeoff('trim house',100,'LF',{building:'House'}),takeoff('trim barn',null,'LF',{basis:'uncertain',building:'Barn'})]});assert.deepEqual(fields({service:'handyman',taskList:'Install trim'},x),[]);});
test('source prompt filtering does not mutate extraction or answers',()=>{const a=build();const x=extraction();const before=JSON.stringify({a,x});fields(a,x,['garageSqft']);assert.equal(JSON.stringify({a,x}),before);});
// Changed on purpose 2026-09-20: the owner's master price book prices four tiers for every service,
// and its lowest, Builder Grade, is the production-builder spec a new build is priced at.
test('integration: new builds offer every price-book finish tier, including Builder Grade',()=>assert.deepEqual(finishOptionsForService('new-construction'),['refresh','mid-range','high-end','luxury']));
test('integration: complete scope reaches review without repeated questions',()=>assert.deepEqual(scopeQuestions(build(),null),[]));
test('integration: exact project-specific clarification wording is preserved',()=>{const q=scopeQuestions({service:'handyman',taskList:'Replace a water heater'},extraction({clarifications:[{field:'plumbing',question:'What tank capacity should the garage water heater have?',reason:'Capacity changes the product cost'}]}));assert.equal(q[0].reason,'What tank capacity should the garage water heater have?');});
test('integration: instruction gates and question UI discard the same excluded trade question',()=>{const a={service:'handyman',taskList:'Install baseboard trim',trimLf:'200',estimatingInstructions:'Price only trim'};const x=extraction({instructions:instructions({inclusions:['Trim only'],questions:['What electrical panel size is needed?']})});assert.deepEqual(instructionPrompts(x,a),[]);assert.deepEqual(scopeQuestions(a,x),[]);});
test('integration: actual service conflict is resolved before any technical questions',()=>{const q=scopeQuestions(build(),null,[{field:'service',values:['new-construction','kitchen'],explanation:'Confirm the scope being requested.'}]);assert.equal(q.length,1);assert.equal(q[0].field,'service');});
test('integration: an explicitly skipped unknown remains an allowance, not a repeated question',()=>assert.deepEqual(scopeQuestions({service:'handyman',taskList:'Install trim'},null,[],['trimLf']),[]));


test('regression: room-level quantity covers the selected bathroom assembly',()=>assert.deepEqual(scopeQuestions({service:'bathroom',sqft:'80',materials:'Porcelain tile',finish:'mid-range',demolition:'Remove tile and vanity'},null),[]));
test('regression: known cabinet runs are already a description of the requested cabinet work',()=>assert.deepEqual(scopeQuestions({service:'cabinet-install',cabinetRoom:'kitchen',cabinetBaseLf:'20',cabinetUpperLf:'0',finish:'mid-range'},null,[],[],['cabinetBaseLf','cabinetUpperLf']),[]));
test('regression: optional location prompts do not reappear as mandatory follow-ups',()=>assert.deepEqual(scopeQuestions(build(),extraction({clarifications:[{field:'location',question:'What is the street address?',reason:'Optional visit detail'}]})),[]));
test('regression: pending cabinet questions are not discarded merely because quantities are unknown',()=>{const x=extraction({instructions:instructions({questions:['What are the cabinet lengths?','What is the cabinet room type?']})});const q=scopeQuestions({service:'cabinet-install',cabinetBaseLf:'20'},x);assert.equal(q[0].field,'cabinetUpperLf');});
test('regression: a numeric input is paired with a numeric answer prompt',()=>{const a={service:'bathroom',sqft:'80',materials:'Porcelain tile',demolition:'Remove tile',finish:'mid-range'};const x=extraction({clarifications:[{field:'fixtureCount',question:'Which fixtures and who supplies them?',reason:'Scope'}]});assert.deepEqual(scopeQuestions(a,x),[]);assert.match(scopeQuestions(a,x,[],[],['fixtureCount'])[0].reason,/number of fixtures/i);});
test('owner-supplied cabinets leave nothing to budget a finish tier for (live Cabinet, 2026-09-25)',()=>{
  const owned={service:'cabinet-install',cabinetRoom:'kitchen',cabinetBaseLf:'10',cabinetUpperLf:'10',cabinetTallLf:'0',location:'Boise'};
  const text='Install 10 linear feet of owner-supplied base cabinets and 10 linear feet of owner-supplied upper cabinets in a kitchen in Boise. The cabinets are already on site. The contractor supplies normal fastening and leveling consumables.';
  assert.ok(!fields(owned,null,[],text).includes('finish'),'no finish question for owner-supplied cabinets');
  assert.ok(!scopeQuestions(owned,null,[],[],[],text).some(q=>q.field==='finish'));
  const supplied='Supply and install 10 linear feet of new base cabinets and 10 linear feet of upper cabinets in the kitchen.';
  assert.ok(fields(owned,null,[],supplied).includes('finish'),'cabinets the contractor supplies still ask which tier');
});
