/**
 * The daily financial report, in the panel: today's (or the latest) report
 * rendered natively, plus send history. The email and this page assemble
 * from the same stored payload, so they can never disagree.
 */

import { checkDatabase, describeSchemaError, query } from "../../../lib/db.ts";
import { isQboConnected } from "../../../lib/finance/qbo/oauth.ts";
import {
  diffReports,
  loadPreviousReport,
  type DailyReport,
  type ProjectCard,
} from "../../../lib/finance/daily-report.ts";
import { money } from "../queries.ts";
import { generateAndSendNow } from "./actions.ts";

export const dynamic = "force-dynamic";

function HealthChip({ health }: { health: ProjectCard["health"] }) {
  const cls =
    health === "ACTION REQUIRED"
      ? "fin-chip fin-chip-critical"
      : health === "WATCH"
        ? "fin-chip fin-chip-warning"
        : "fin-chip fin-chip-green";
  return <span className={cls}>{health}</span>;
}

export default async function DailyReportPage() {
  const db = await checkDatabase();
  if (!db.ok) {
    return (
      <main className="admin-main">
        <h1 className="admin-h1">Daily report</h1>
        <div className="admin-notice admin-notice-error">
          <strong>Database unavailable</strong>
          {db.detail}
        </div>
      </main>
    );
  }

  // checkDatabase only proves the first migration ran, so this table can still
  // be missing on a database that has not had every migration applied. That
  // has to read as "run the migrations", not as a blank error page.
  type Row = {
    covers_date: string;
    payload: DailyReport;
    emailed_to: string[] | null;
    email_status: string | null;
    created_at: Date;
  };
  let rows: Row[];
  try {
    rows = await query<Row>(
      `SELECT covers_date::text, payload, emailed_to, email_status, created_at
       FROM daily_report ORDER BY covers_date DESC LIMIT 15`,
    );
  } catch (error) {
    const problem = describeSchemaError(error);
    return (
      <main className="admin-main">
        <h1 className="admin-h1">Daily financial snapshot</h1>
        <div className="admin-notice admin-notice-error">
          <strong>{problem.problem}</strong>
          {problem.detail}
        </div>
        <p className="lead-note">
          No report data has been lost. The daily job stores each report by
          date, so once this is fixed the history is still there.
        </p>
      </main>
    );
  }

  const latest = rows[0] ?? null;
  const report = latest?.payload ?? null;
  const previous = report ? await loadPreviousReport(report.coversDate) : null;
  const changes = report ? diffReports(previous, report) : [];

  // A stored report keeps whatever was true when it was generated - that is the
  // point, so the emailed copy and this page can never disagree. But a report
  // that says "QuickBooks is not connected" while the connection is live reads
  // as a broken integration rather than an old snapshot, so say which it is.
  const connectedNow = await isQboConnected();
  const reportSaysDisconnected = Boolean(
    report?.limitations?.some((line) => line.includes("QuickBooks is not connected")),
  );
  const staleOnConnection = connectedNow && reportSaysDisconnected;

  return (
    <main className="admin-main">
      <h1 className="admin-h1">Daily financial snapshot</h1>
      <p className="admin-sub">
        The same report emailed to {`accounting@p5homeco.com`} each day, viewable
        here with history. Generated by the daily finance job.
      </p>

      <form action={generateAndSendNow} style={{ marginBottom: 22 }}>
        <button className="lead-action" type="submit">
          Generate &amp; send now
        </button>
      </form>

      {staleOnConnection && (
        <div className="admin-notice">
          <strong>This report predates the QuickBooks connection</strong>
          It was generated while QuickBooks was still disconnected, so it carries no
          financial figures. The connection is live now — regenerate above for current
          numbers, or wait for tomorrow&rsquo;s scheduled pass.
        </div>
      )}

      {!report ? (
        <div className="admin-empty">
          <h2>No report yet</h2>
          <p>
            The daily job has not produced a report. Use Generate &amp; send
            now, or check Health if the job should have run.
          </p>
        </div>
      ) : (
        <>
          <p className="admin-sub">
            Covers <b>{report.coversDate}</b>
            {latest?.email_status ? ` · email: ${latest.email_status}` : ""}
            {report.lastSyncAt
              ? ` · data synced ${new Date(report.lastSyncAt).toLocaleString("en-US")}`
              : ""}
          </p>

          {(report.limitations ?? []).length > 0 && (
            <div className="admin-notice">
              <strong>Data notes</strong>
              {(report.limitations ?? []).join(" ")}
            </div>
          )}

          <div className="fin-section">
            <h2>Needs your attention</h2>
            {(report.attention?.items ?? []).length === 0 ? (
              <p className="lead-ok">No significant financial issues requiring attention.</p>
            ) : (
              <div className="admin-cards">
                {(report.attention?.items ?? []).map((item, i) => (
                  <article
                    key={i}
                    className={
                      item.severity === "critical"
                        ? "lead-card lead-card-critical"
                        : "lead-card lead-card-warn"
                    }
                  >
                    <div className="lead-top">
                      <h3 className="lead-name" style={{ fontSize: 17 }}>
                        {item.title}
                      </h3>
                      <span className={`fin-chip fin-chip-${item.severity}`}>{item.severity}</span>
                    </div>
                    <div className="lead-meta">
                      {item.amount !== null && (
                        <div>
                          <b>Amount</b>
                          {money(item.amount)}
                        </div>
                      )}
                      {item.dueOn && (
                        <div>
                          <b>Due</b>
                          {item.dueOn}
                        </div>
                      )}
                      {item.recommendedAction && (
                        <div>
                          <b>Recommended</b>
                          {item.recommendedAction}
                        </div>
                      )}
                    </div>
                  </article>
                ))}
              </div>
            )}
          </div>

          {report.company && (
            <div className="fin-section">
              <h2>Company snapshot</h2>
              <div className="fin-hero">
                <div className="admin-stat">
                  <b>{money(report.company.cash.total)}</b>
                  <span>Cash</span>
                </div>
                <div
                  className={`admin-stat${report.company.safeCashProvisional ? " fin-provisional" : ""}${report.company.safeCash < 0 ? " fin-negative" : ""}`}
                >
                  <b>{money(report.company.safeCash)}</b>
                  <span>Safe cash{report.company.safeCashProvisional ? " (prov.)" : ""}</span>
                </div>
                <div className="admin-stat">
                  <b>{money(report.company.ar.total)}</b>
                  <span>Receivables</span>
                </div>
                <div className={`admin-stat${report.company.ar.overdue > 0 ? " admin-stat-alarm" : ""}`}>
                  <b>{money(report.company.ar.overdue)}</b>
                  <span>Overdue AR</span>
                </div>
                <div className="admin-stat">
                  <b>{money(report.company.ap.total)}</b>
                  <span>Payables</span>
                </div>
                <div className="admin-stat">
                  <b>{money(report.company.ap.dueSoon)}</b>
                  <span>Due in 7 days</span>
                </div>
              </div>
              <div className="fin-table-wrap">
                <table className="fin-table">
                  <thead>
                    <tr>
                      <th></th>
                      <th className="fin-num">Today</th>
                      <th className="fin-num">Month to date</th>
                      <th className="fin-num">Year to date</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Invoiced</td>
                      <td className="fin-num">{money(report.company.activity.today.invoiced)}</td>
                      <td className="fin-num">{money(report.company.activity.mtd.invoiced)}</td>
                      <td className="fin-num">{money(report.company.activity.ytd.invoiced)}</td>
                    </tr>
                    <tr>
                      <td>Collected</td>
                      <td className="fin-num">{money(report.company.activity.today.collected)}</td>
                      <td className="fin-num">{money(report.company.activity.mtd.collected)}</td>
                      <td className="fin-num">{money(report.company.activity.ytd.collected)}</td>
                    </tr>
                    <tr>
                      <td>Bills entered</td>
                      <td className="fin-num">{money(report.company.activity.today.billsEntered)}</td>
                      <td className="fin-num">{money(report.company.activity.mtd.billsEntered)}</td>
                      <td className="fin-num">{money(report.company.activity.ytd.billsEntered)}</td>
                    </tr>
                    <tr>
                      <td>Bills paid</td>
                      <td className="fin-num">{money(report.company.activity.today.billsPaid)}</td>
                      <td className="fin-num">{money(report.company.activity.mtd.billsPaid)}</td>
                      <td className="fin-num">{money(report.company.activity.ytd.billsPaid)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          )}

          <div className="fin-section">
            <h2>What changed since yesterday</h2>
            {changes.length === 0 ? (
              <p className="lead-note">No meaningful changes.</p>
            ) : (
              <ul style={{ margin: 0, paddingLeft: 20, display: "grid", gap: 6, fontSize: 14 }}>
                {changes.map((ch, i) => (
                  <li key={i}>
                    {ch.text}
                    {ch.amount !== null ? ` (${money(ch.amount)})` : ""}
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div className="fin-section">
            <h2>Active projects</h2>
            {(report.projects ?? []).length === 0 ? (
              <p className="lead-note">No active projects.</p>
            ) : (
              <div className="admin-cards">
                {(report.projects ?? []).map((p) => (
                  <article key={p.p5Id} className="lead-card">
                    <div className="lead-top">
                      <h3 className="lead-name" style={{ fontSize: 18 }}>
                        {p.p5Id} {p.name}
                      </h3>
                      <HealthChip health={p.health} />
                    </div>
                    <div className="lead-tags">
                      <span className="lead-tag lead-tag-brand">{p.division}</span>
                      {p.customer && <span className="lead-tag">{p.customer}</span>}
                      <span className="lead-tag">{p.status}</span>
                    </div>
                    <div className="lead-meta lead-meta-wide">
                      <div>
                        <b>Contract</b>
                        {money(p.contractValue)}
                      </div>
                      <div>
                        <b>Budget</b>
                        {p.currentBudget > 0 ? money(p.currentBudget) : "Not set"}
                      </div>
                      <div>
                        <b>Spent</b>
                        {money(p.actualCost)}
                      </div>
                      <div>
                        <b>Committed</b>
                        {money(p.committed)}
                      </div>
                      <div>
                        <b>Remaining</b>
                        {p.remainingBudget === null ? "n/a" : money(p.remainingBudget)}
                      </div>
                      <div>
                        <b>Budget used</b>
                        {p.budgetUsedPct === null ? "n/a" : `${p.budgetUsedPct.toFixed(0)}%`}
                      </div>
                      <div>
                        <b>Collected</b>
                        {money(p.paymentsReceived)}
                      </div>
                      <div>
                        <b>Customer balance</b>
                        {money(p.customerBalance)}
                      </div>
                      <div>
                        <b>Open invoices</b>
                        {money(p.outstandingInvoices)}
                      </div>
                      <div>
                        <b>Open bills</b>
                        {money(p.outstandingBills)}
                      </div>
                      <div>
                        <b>Projected margin</b>
                        {p.projectedMarginPct === null
                          ? "n/a"
                          : `${p.projectedMarginPct.toFixed(1)}% (goal ${p.targetMarginPct}%)`}
                      </div>
                      <div>
                        <b>Projected profit</b>
                        {money(p.projectedGrossProfit)}
                      </div>
                    </div>
                    <p className="lead-why" style={{ marginTop: 12 }}>
                      {(p.healthReasons ?? []).join("; ")}
                    </p>
                    {(p.problems ?? []).map((problem) => (
                      <p key={problem} className="lead-error lead-error-block" style={{ marginTop: 8 }}>
                        Data: {problem}
                      </p>
                    ))}
                  </article>
                ))}
              </div>
            )}
          </div>

          <div className="fin-section">
            <h2>Upcoming (14 days)</h2>
            {(report.upcoming ?? []).length === 0 ? (
              <p className="lead-note">Nothing due in the next 14 days.</p>
            ) : (
              <div className="fin-table-wrap">
                <table className="fin-table">
                  <thead>
                    <tr>
                      <th>Due</th>
                      <th>What</th>
                      <th>Who</th>
                      <th className="fin-num">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(report.upcoming ?? []).slice(0, 12).map((u, i) => (
                      <tr key={i}>
                        <td>{u.dueDate ?? "no date"}</td>
                        <td>{u.kind === "bill" ? "Pay bill" : "Expect payment"}</td>
                        <td>{u.counterparty ?? "-"}</td>
                        <td className="fin-num">{money(u.amount)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {rows.length > 1 && (
            <div className="fin-section">
              <h2>History</h2>
              <div className="fin-table-wrap">
                <table className="fin-table">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Email</th>
                      <th>Recipients</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rows.map((r) => (
                      <tr key={r.covers_date}>
                        <td>{r.covers_date}</td>
                        <td>{r.email_status ?? "-"}</td>
                        <td>{(r.emailed_to ?? []).join(", ") || "-"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
    </main>
  );
}
