import {test} from 'node:test';
import assert from 'node:assert/strict';
import {requestBody,parseReply,Reader} from '../src/provider.mjs';
import {REVIEW_SCHEMA,EVIDENCE_SCHEMA} from '../src/contracts.mjs';
const review=()=>({summary:'Synthetic QA',facts:[],conflicts:[],missingInformation:[],reviewNotes:[],clarifications:[],instructions:{inclusions:[],exclusions:[],responsibilities:[],buildings:[],floors:[],separateBuildings:false,laborOnly:false,materialsOnly:false,questions:[]},pages:[],takeoffs:[]});
const toolName='submit_document_review';
const reply=input=>({stop_reason:'tool_use',content:[{type:'tool_use',id:'test-call',name:toolName,input}]});
test('Anthropic review avoids compiled grammar and retains the entire output contract',()=>{
 const before=JSON.stringify(REVIEW_SCHEMA);
 const request=requestBody('anthropic','test','vocabulary',{},[],REVIEW_SCHEMA,1024,'review');
 assert.equal(request.body.output_config,undefined);
 assert.equal(request.body.tools.length,1);
 assert.equal(request.body.tools[0].strict,false);
 assert.deepEqual(request.body.tools[0].input_schema,REVIEW_SCHEMA);
 assert.deepEqual(request.body.tool_choice,{type:'tool',name:toolName,disable_parallel_tool_use:true});
 assert.equal(request.outputTool,toolName);
 assert.equal(JSON.stringify(REVIEW_SCHEMA),before);
 const evidence=requestBody('anthropic','test','',{},[],EVIDENCE_SCHEMA,1024,'read');
 assert.deepEqual(evidence.body.output_config.format.schema,EVIDENCE_SCHEMA);
 assert.equal(evidence.body.tools,undefined);
 assert.deepEqual(requestBody('openai','test','',{},[],REVIEW_SCHEMA,1024,'review').body.text.format.schema,REVIEW_SCHEMA);
 assert.deepEqual(requestBody('gemini','test','',{},[],REVIEW_SCHEMA,1024,'review').body.generationConfig.responseJsonSchema,REVIEW_SCHEMA);
});
for(const location of ['facts','conflicts','clarifications','missing','extra','quantity','string','valid'])test('Reader validates full tool payload: '+location,async()=>{
 let result=review();
 if(location==='facts')result.facts=[{field:'unknownField',value:'4',confidence:1,source:'QA.pdf',evidence:'four doors',basis:'stated'}];
 if(location==='conflicts')result.conflicts=[{field:'unknownField',values:['1','2'],explanation:'test'}];
 if(location==='clarifications')result.clarifications=[{field:'unknownField',question:'test?',reason:'test'}];
 if(location==='missing')delete result.instructions;
 if(location==='extra')result.uncheckedResult='not allowed';
 if(location==='quantity')result.takeoffs=[{id:'doors',description:'Doors',building:'',floor:'',component:'door',quantity:'4',unit:'each',basis:'stated',evidence:'4 doors',sources:[],supersedes:[],issues:[]}];
 if(location==='string')result=JSON.stringify(result);
 let released=0,calls=0;
 const config={provider:'anthropic',model:'test',verifyModel:'test',key:'synthetic',tpm:100000,maxOutput:2048,callMs:1000};
 const store={reserve:async()=> 'slot',release:async()=>released++,metric:async()=>{}};
 const reader=new Reader(config,store,async(url,options)=>{
  calls++;
  const body=JSON.parse(options.body);
  assert.equal(body.output_config,undefined);
  assert.deepEqual(body.tools[0].input_schema,REVIEW_SCHEMA);
  return new Response(JSON.stringify(reply(result)));
 });
 const call=reader.call({kind:'review'},'vocabulary',{},[],REVIEW_SCHEMA,new AbortController().signal);
 if(location==='valid')assert.deepEqual(await call,result);
 else await assert.rejects(call,/invalid-provider-schema|invalid-provider-tool-json/);
 assert.equal(calls,1);assert.equal(released,1);
});
for(const kind of ['truncated','refusal','text-only','wrong-tool','multiple-tools','missing-id'])test('incomplete or ambiguous tool output rejected: '+kind,()=>{
 const response=reply(review());
 if(kind==='truncated')response.stop_reason='max_tokens';
 if(kind==='refusal')response.stop_reason='refusal';
 if(kind==='text-only')response.content=[{type:'text',text:JSON.stringify(review())}];
 if(kind==='wrong-tool')response.content[0].name='send_email';
 if(kind==='multiple-tools')response.content.push({...response.content[0],id:'second-call'});
 if(kind==='missing-id')delete response.content[0].id;
 assert.throws(()=>parseReply('anthropic',response,toolName),/provider-output-incomplete|provider-output-limit|invalid-provider-tool-output/);
});
test('tool output is not accepted by the evidence text path',()=>{
 assert.throws(()=>parseReply('anthropic',reply({pages:[]})),/provider-output-incomplete/);
});
