"use client";

/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";

type CompanyKey = "construction" | "remodeling" | "cabinetry" | "handyman";

const companyDetails: Record<CompanyKey, { name: string; reason: string; url: string; cta: string; label: string; options: string[] }> = {
  construction: { name: "Boise Construction Co", reason: "The design-build team for new homes, land evaluation, plans, permitting, and construction from the ground up.", url: "https://boiseconstruction.co", cta: "Visit Boise Construction Co", label: "Build a new home", options: ["Custom home", "Semi-custom home", "Build on land I own", "Home plans or lot evaluation"] },
  remodeling: { name: "Boise Remodeling Co", reason: "The accountable design-build team for major renovations, additions, and projects that change how your existing home works.", url: "https://boiseremodeling.co", cta: "Visit Boise Remodeling Co", label: "Remodel my home", options: ["Kitchen remodel", "Bathroom remodel", "Whole-home remodel", "Addition, ADU, or basement"] },
  cabinetry: { name: "Boise Cabinet Co", reason: "The cabinetry specialists for made-to-order kitchens, vanities, built-ins, and coordinated storage throughout the home.", url: "https://boisecabinet.co", cta: "Visit Boise Cabinet Co", label: "Plan custom cabinets", options: ["Kitchen cabinets", "Bathroom vanity", "Built-ins or storage", "Whole-home cabinetry"] },
  handyman: { name: "Boise Handyman Co", reason: "The skilled home-repair team for finish work, installations, maintenance, and the smaller projects that still deserve professional care.", url: "tel:+12084771169", cta: "Call for handyman service", label: "Complete repairs", options: ["Drywall or trim repair", "Mounting or installation", "Deck or exterior repair", "A multi-item home list"] },
};

const Arrow = ({ diagonal = false }: { diagonal?: boolean }) => <span aria-hidden="true" className={diagonal ? "arrow arrow-diagonal" : "arrow"}>{diagonal ? "↗" : "→"}</span>;

const Wordmark = ({ light = false }: { light?: boolean }) => (
  <a className={`wordmark ${light ? "wordmark-light" : ""}`} href="#top" aria-label="P5 Home Co, back to top">
    <svg className="p5-symbol" viewBox="0 0 56 56" aria-hidden="true"><rect x="1" y="1" width="54" height="54" /><path d="M12 43V13h10.7c7.8 0 12.2 4 12.2 10.2 0 6.3-4.4 10.3-12.2 10.3h-4.1" /><path className="p5-five" d="M43.5 14H32.9l-1 10.2h5.5c5.8 0 8.8 3.2 8.8 8.4 0 6.4-4.2 10.4-11.2 10.4-2.4 0-4.6-.5-6.4-1.5" /></svg>
    <span className="wordmark-copy"><span>P5 HOME <b>CO</b></span><small>The home company</small></span>
  </a>
);

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [matcherOpen, setMatcherOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 32);
    onScroll(); window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);
  useEffect(() => { document.body.style.overflow = menuOpen || matcherOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menuOpen, matcherOpen]);
  const openMatcher = () => { setMenuOpen(false); setMatcherOpen(true); };

  return (
    <main id="top">
      <header className={`site-header ${scrolled ? "site-header-scrolled" : ""}`}>
        <div className="nav-shell">
          <Wordmark light={!scrolled && !menuOpen} />
          <nav className="desktop-nav" aria-label="Primary navigation"><a href="#companies">Our companies</a><a href="#p5-standard">The P5 standard</a><a href="#about">About</a><a href="#service-area">Service area</a></nav>
          <button className="nav-cta" type="button" onClick={openMatcher}>Find your team <Arrow /></button>
          <button className={`menu-button ${menuOpen ? "menu-button-open" : ""}`} type="button" onClick={() => setMenuOpen((value) => !value)} aria-expanded={menuOpen} aria-controls="mobile-menu" aria-label={menuOpen ? "Close menu" : "Open menu"}><span /><span /></button>
        </div>
        <div id="mobile-menu" className={`mobile-menu ${menuOpen ? "mobile-menu-open" : ""}`}><div className="mobile-menu-inner"><p>Explore P5 Home Co</p><nav aria-label="Mobile navigation"><a href="#companies" onClick={() => setMenuOpen(false)}>Our companies <Arrow /></a><a href="#p5-standard" onClick={() => setMenuOpen(false)}>The P5 standard <Arrow /></a><a href="#about" onClick={() => setMenuOpen(false)}>About P5 <Arrow /></a><a href="#service-area" onClick={() => setMenuOpen(false)}>Service area <Arrow /></a></nav><button className="button button-light" type="button" onClick={openMatcher}>Find your team <Arrow /></button></div></div>
      </header>

      <section className="hero" aria-labelledby="hero-heading">
        <img className="hero-image" src="/images/p5-hero.webp" alt="Contemporary Treasure Valley home at sunrise" /><div className="hero-shade" /><div className="hero-grain" />
        <div className="hero-content content-shell"><div className="hero-copy"><p className="eyebrow eyebrow-light">The P5 Home Co family of companies</p><h1 id="hero-heading">One home.<br />Four expert teams.</h1><p className="hero-lede">Build it. Remodel it. Finish it. Care for it. P5 brings every chapter of homeownership under one trusted family of specialized Treasure Valley companies.</p><div className="hero-actions"><button className="button button-light" type="button" onClick={openMatcher}>Find the right team <Arrow /></button><a className="text-link text-link-light" href="#companies">Meet the companies <Arrow /></a></div></div><div className="hero-side-note"><span>Serving</span><strong>Boise and the<br />Treasure Valley</strong></div></div>
        <a className="scroll-cue" href="#about" aria-label="Explore P5 Home Co"><span>Explore</span><i /></a>
      </section>

      <section className="trust-strip" aria-label="P5 Home Co credentials"><div className="content-shell trust-grid"><div><strong>Est. 2020</strong><span>Local experience</span></div><div><strong>100+ projects</strong><span>Across the Treasure Valley</span></div><div><strong>Bonded and insured</strong><span>Professional protection</span></div><div><strong>Ada and Canyon</strong><span>Local permit knowledge</span></div></div></section>

      <section id="about" className="manifesto section-pad"><div className="content-shell manifesto-layout"><div className="manifesto-title"><p className="eyebrow">More than a holding company</p><h2>The right specialist.<br />One shared standard.</h2></div><div className="manifesto-copy"><p className="lead-copy">P5 Home Co is the operating family behind four focused home-service companies. It is not a directory or referral network.</p><p>Each company has its own craft, team, and expertise. What connects them is the way the work is handled: clear scopes, accountable communication, local knowledge, and respect for the home.</p><p>You get a specialist for the project in front of you, with an established family of companies ready for whatever your home needs next.</p><button className="text-link" type="button" onClick={openMatcher}>Match me with a company <Arrow /></button></div></div></section>

      <section id="companies" className="companies section-pad"><div className="content-shell"><div className="companies-heading"><div><p className="eyebrow eyebrow-light">The P5 family</p><h2>Four disciplines.<br />One complete home company.</h2></div><p>Choose the team built around your scope. If a project crosses specialties, the companies can coordinate the handoff without leaving you to assemble the pieces.</p></div><div className="company-index"><a href="#construction"><span>01</span><strong>Build</strong><small>Boise Construction Co</small><Arrow /></a><a href="#remodeling"><span>02</span><strong>Remodel</strong><small>Boise Remodeling Co</small><Arrow /></a><a href="#cabinetry"><span>03</span><strong>Finish</strong><small>Boise Cabinet Co</small><Arrow /></a><a href="#handyman"><span>04</span><strong>Care</strong><small>Boise Handyman Co</small><Arrow /></a></div></div></section>

      <BrandPanel id="construction" number="01" category="New home building" logo="/brands/boise-construction-co.svg" image="/images/p5-construction-v2.webp" alt="Custom home under construction in Idaho's Treasure Valley" caption="Ground-up construction · Treasure Valley" headline={<>From bare lot<br />to the keys.</>} className="brand-construction" description="Custom and semi-custom homes planned around your lot, budget, and the way you want to live. Design, engineering, permitting, and construction stay with one accountable team." services={["Custom home building", "Semi-custom homes", "Build on your lot", "Home design and plans"]} proof="Line-item budget before construction" url="https://boiseconstruction.co" linkLabel="Explore Boise Construction Co" />
      <BrandPanel id="remodeling" number="02" category="Design-build remodeling" logo="/brands/boise-remodeling-co-dark.svg" image="/images/p5-remodel.webp" alt="Warm, refined whole-home remodel interior" caption="Design-build remodeling · Boise, Idaho" headline={<>Reimagine the<br />home you love.</>} className="brand-remodeling" reverse description="Major renovations managed under one roof, with design direction, a written scope, permits, and construction coordinated by a dedicated project team." services={["Kitchen remodeling", "Bathroom remodeling", "Whole-home remodeling", "Additions and ADUs"]} proof="Written progress update every Friday" url="https://boiseremodeling.co" linkLabel="Explore Boise Remodeling Co" />
      <BrandPanel id="cabinetry" number="03" category="Custom cabinetry" logo="/brands/boise-cabinet-co-dark.svg" image="/images/p5-cabinet.webp" alt="Custom white oak and cream cabinetry detail" caption="Custom cabinetry · Designed for your space" headline={<>Made to fit.<br />Built to last.</>} className="brand-cabinetry" description="Premium frameless cabinetry designed, built, and installed for the way you live, from the first layout and finish selection through the final walkthrough." services={["Kitchen cabinetry", "Bathroom vanities", "Built-ins and storage", "Whole-home cabinetry"]} proof="299 finishes · Lifetime workmanship warranty" url="https://boisecabinet.co" linkLabel="Explore Boise Cabinet Co" />
      <BrandPanel id="handyman" number="04" category="Home repair and maintenance" image="/images/p5-handyman.webp" alt="Skilled home repair professional completing finish work" caption="Repair, installation, and home care · Treasure Valley" headline={<>Your list.<br />Handled right.</>} className="brand-handyman" reverse description="Dependable skilled help for repairs, installations, and finishing projects. The same care and accountability, sized for the work that keeps your home working well." services={["Drywall and trim repair", "TV and fixture mounting", "Deck and exterior repair", "General home maintenance"]} proof="One list · One skilled local team" url="tel:+12084771169" linkLabel="Call for handyman service" comingSoon />

      <section id="p5-standard" className="standard section-pad"><div className="content-shell"><div className="standard-heading"><div><p className="eyebrow eyebrow-light">What P5 adds</p><h2>Four companies should feel like one good experience.</h2></div><p>Specialization should create confidence, not more coordination. These are the operating expectations that connect every P5 company.</p></div><div className="standard-grid"><Standard number="01" title="Clarity before commitment">Planning guidance and written scope details help you understand the work before it begins.</Standard><Standard number="02" title="One accountable team">You know who owns the next step, who to contact, and where the project stands.</Standard><Standard number="03" title="Proactive communication">Decisions, schedule changes, and budget impacts are raised early and documented clearly.</Standard><Standard number="04" title="A connected handoff">When another specialty is needed, P5 can route the project to the right team without sending you back to square one.</Standard></div><div className="process-proof"><span>Built into the process</span><ul><li>Written scopes</li><li>Permits handled in-house where required</li><li>Dedicated project ownership</li><li>Workmanship support</li></ul></div></div></section>

      <section className="handoff section-pad"><div className="content-shell handoff-layout"><div><p className="eyebrow">Connected when it matters</p><h2>One project can need more than one expert.</h2></div><div className="handoff-example"><span className="handoff-kicker">Example · A complete kitchen transformation</span><Handoff number="01" company="Boise Remodeling Co">Layout, permits, demolition, and construction</Handoff><Handoff number="02" company="Boise Cabinet Co">Cabinet design, fabrication, and installation</Handoff><Handoff number="03" company="Boise Handyman Co">Final mounting, finish work, and punch-list items</Handoff></div></div></section>

      <section id="service-area" className="service-area section-pad"><div className="content-shell service-area-grid"><div><p className="eyebrow">Our home is the Treasure Valley</p><h2>Local teams.<br />Valley-wide reach.</h2><p className="service-area-copy">P5 companies serve homeowners across Ada and Canyon counties, with practical knowledge of local homes, permitting offices, building conditions, and communities.</p><button className="text-link" type="button" onClick={openMatcher}>Choose your company <Arrow /></button></div><div className="area-list" aria-label="Cities served"><span>Boise</span><span>Meridian</span><span>Eagle</span><span>Nampa</span><span>Kuna</span><span>Star</span><span>Middleton</span><span>Caldwell</span></div></div></section>

      <section className="final-cta"><img src="/images/p5-closing-v2.webp" alt="Warm Treasure Valley home at blue hour" /><div className="final-cta-shade" /><div className="content-shell final-cta-content"><p className="eyebrow eyebrow-light">Start with the need, not the company</p><h2>Tell us what you are planning.<br />We will point you to the right team.</h2><button className="button button-light" type="button" onClick={openMatcher}>Find my P5 company <Arrow /></button></div></section>

      <footer className="site-footer"><div className="content-shell"><div className="footer-main"><div className="footer-brand"><Wordmark light /><p>Four specialized home-service companies. One shared standard for the Treasure Valley.</p><a className="footer-phone" href="tel:+12084771169">(208) 477-1169</a></div><div className="footer-links"><div><h3>Our companies</h3><External href="https://boiseconstruction.co">Boise Construction Co</External><External href="https://boiseremodeling.co">Boise Remodeling Co</External><External href="https://boisecabinet.co">Boise Cabinet Co</External><span className="footer-soon">Boise Handyman Co <small>Launching soon</small></span></div><div><h3>Explore</h3><a href="#about">About P5 Home Co</a><a href="#p5-standard">The P5 standard</a><a href="#service-area">Service area</a><button type="button" onClick={openMatcher}>Find your team</button></div></div></div><div className="footer-bottom"><span>© 2026 P5 Home Co. All rights reserved.</span><span>Boise and the Treasure Valley, Idaho</span></div></div></footer>
      {matcherOpen && <ProjectMatcher onClose={() => setMatcherOpen(false)} />}
    </main>
  );
}

function BrandPanel({ id, number, category, logo, image, alt, caption, headline, className, reverse = false, description, services, proof, url, linkLabel, comingSoon = false }: { id: string; number: string; category: string; logo?: string; image: string; alt: string; caption: string; headline: React.ReactNode; className: string; reverse?: boolean; description: string; services: string[]; proof: string; url: string; linkLabel: string; comingSoon?: boolean }) {
  const external = url.startsWith("http");
  return <section id={id} className={`brand-panel ${reverse ? "brand-panel-reverse" : ""} ${className}`}><div className="brand-image-wrap"><img src={image} alt={alt} /><span className="image-caption">{caption}</span></div><div className="brand-content"><div className="brand-topline"><span>{number}</span><span>{category}</span></div>{logo ? <img className="brand-logo" src={logo} alt="" aria-hidden="true" /> : <div className="handyman-wordmark"><span>BOISE</span><strong>HANDYMAN <b>CO</b></strong></div>}<h3>{headline}</h3><p>{description}</p><ul className="service-list">{services.map((service) => <li key={service}>{service}</li>)}</ul><div className="brand-proof"><span aria-hidden="true">✓</span>{proof}</div><a className="brand-link" href={url} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined}>{linkLabel} <Arrow diagonal={external} /></a>{comingSoon && <span className="launch-note">Full website launching soon</span>}</div></section>;
}

function Standard({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <article><span>{number}</span><h3>{title}</h3><p>{children}</p></article>; }
function Handoff({ number, company, children }: { number: string; company: string; children: React.ReactNode }) { return <div className="handoff-step"><b>{number}</b><span><strong>{company}</strong><small>{children}</small></span></div>; }
function External({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} target="_blank" rel="noreferrer">{children} <Arrow diagonal /></a>; }

function ProjectMatcher({ onClose }: { onClose: () => void }) {
  const [company, setCompany] = useState<CompanyKey | null>(null);
  const [project, setProject] = useState<string | null>(null);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose]);
  const detail = company ? companyDetails[company] : null;
  const step = project ? 3 : company ? 2 : 1;
  return <div className="matcher" role="dialog" aria-modal="true" aria-labelledby="matcher-title"><button className="matcher-backdrop" type="button" aria-label="Close company matcher" onClick={onClose} /><div className="matcher-panel"><div className="matcher-header"><Wordmark /><div className="matcher-progress"><span>0{step}</span><i><b style={{ width: `${step * 33.333}%` }} /></i><span>03</span></div><button className="matcher-close" type="button" onClick={onClose} aria-label="Close company matcher">×</button></div><div className="matcher-body">
    {!company && <><p className="eyebrow">Step 1 · Your goal</p><h2 id="matcher-title">What does your home need?</h2><p className="matcher-intro">Choose the closest match. We will narrow it down from there.</p><div className="matcher-choices">{(Object.keys(companyDetails) as CompanyKey[]).map((key, index) => <button key={key} type="button" onClick={() => setCompany(key)}><span>0{index + 1}</span><strong>{companyDetails[key].label}</strong><Arrow /></button>)}</div></>}
    {company && !project && detail && <><button className="matcher-previous" type="button" onClick={() => setCompany(null)}>← Back</button><p className="eyebrow">Step 2 · Project type</p><h2 id="matcher-title">Tell us a little more.</h2><p className="matcher-intro">Which option best describes the work?</p><div className="matcher-choices">{detail.options.map((option, index) => <button key={option} type="button" onClick={() => setProject(option)}><span>0{index + 1}</span><strong>{option}</strong><Arrow /></button>)}</div></>}
    {company && project && detail && <div className={`matcher-result matcher-result-${company}`}><button className="matcher-previous" type="button" onClick={() => setProject(null)}>← Back</button><p className="eyebrow">Your P5 match</p><span className="result-overline">Recommended for · {project}</span><h2 id="matcher-title">{detail.name}</h2><p>{detail.reason}</p><div className="result-actions"><a className="button button-dark" href={detail.url} target={detail.url.startsWith("http") ? "_blank" : undefined} rel={detail.url.startsWith("http") ? "noreferrer" : undefined}>{detail.cta} <Arrow diagonal={detail.url.startsWith("http")} /></a><button className="text-link" type="button" onClick={() => { onClose(); document.getElementById(company)?.scrollIntoView({ behavior: "smooth" }); }}>See why it fits <Arrow /></button></div><small>No form. No obligation. You are choosing where to continue.</small></div>}
  </div></div></div>;
}
