'use client';
import {useState} from 'react';
import type {ProjectRecord,RecordProblem} from '../lib/p5/projectRecord';
import type {ProjectChange} from '../lib/p5/projectConversation';
import P5EstimateDetails from './P5EstimateDetails';
import estimateStyles from './P5Estimator.module.css';
import styles from './P5ProjectReview.module.css';
type Snapshot={attempts?:unknown[];draftRevision:number;current:boolean;saved:{draftRevision:number;record:ProjectRecord;result?:{status?:string;problems?:RecordProblem[];customer?:unknown}}|null;changes:ProjectChange[]};
type ChangeBody={id:string;action:'answer'|'revise';revision:number;recordHash:string;requestId:string;response:string;questionId?:string};
const endpoint='/api/admin/p5-estimators/project-record';
export default function P5ProjectReview(){
 const [id,setId]=useState(''),[loadedId,setLoadedId]=useState(''),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[problems,setProblems]=useState<RecordProblem[]>([]);
 const [answers,setAnswers]=useState<Record<string,string>>({}),[revision,setRevision]=useState(''),[pendingChange,setPendingChange]=useState<ChangeBody|null>(null);
 const record=snapshot?.saved?.record,current=Boolean(snapshot?.current),locked=busy||Boolean(pendingChange);
 async function read(projectId:string){const response=await fetch(endpoint+'?id='+encodeURIComponent(projectId),{cache:'no-store'}),body=await response.json();if(!response.ok)throw new Error(body.error||'Could not load this project.');if(projectId!==loadedId){setAnswers({});setRevision('');}setSnapshot(body);setLoadedId(projectId);setProblems(body.current?body.saved?.result?.problems||[]:[]);}
 async function load(){setBusy(true);setError('');try{await read(id.trim());setMessage('Saved project loaded.');}catch(e){setError(e instanceof Error?e.message:'Project load failed.');}finally{setBusy(false);}}
 async function run(phase:'interpret'|'price'){
  if(!snapshot)return;setBusy(true);setError('');setProblems([]);setMessage('Reviewing the project. Completed stages are saved.');
  try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:loadedId,revision:snapshot.draftRevision,phase})}),body=await response.json();if(!response.ok)throw new Error(body.error||'The review could not finish.');await read(loadedId);if(body.pending)setMessage(body.message+' Use the same review button to resume.');else{setProblems(body.result?.problems||[]);setMessage(body.result?.status==='estimated'?'A preliminary estimate passed the automated checks. Independent estimate review is still required.':body.result?.status==='questions'?'Answer the project questions below.':body.result?.status==='ready'?'Scope review is ready for pricing.':'Review the issues below before continuing.');}}
  catch(e){try{await read(loadedId);}catch{/* Keep the original failure if diagnostics are temporarily unavailable. */}setError((e instanceof Error?e.message:'Review interrupted.')+' Completed stages are preserved. Reload or resume the same review.');}finally{setBusy(false);}
 }
 async function save(body:ChangeBody){
  setPendingChange(body);setBusy(true);setError('');let acknowledged=false,definitiveFailure=false;
  try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok){if(response.status>=400&&response.status<500){definitiveFailure=true;setPendingChange(null);setSnapshot(previous=>previous?{...previous,current:false}:previous);}throw new Error(result.error||'The response could not be saved.');}acknowledged=true;setPendingChange(null);setSnapshot(previous=>previous?{...previous,current:false,draftRevision:result.revision}:previous);setMessage('Response saved. Review the updated scope before generating new prices.');await read(loadedId);}
  catch(e){setError((e instanceof Error?e.message:'Save interrupted.')+(acknowledged?' Your response is saved. Reload the saved project to refresh this screen.':definitiveFailure?' Reload the current project before trying again.':' Retry the same save to confirm its outcome; it will not duplicate an already saved response.'));}finally{setBusy(false);}
 }
 function change(response:string,questionId?:string){if(record&&snapshot&&current&&response.trim())void save({id:loadedId,action:questionId?'answer':'revise',questionId,revision:snapshot.draftRevision,recordHash:record.recordHash,requestId:crypto.randomUUID(),response:response.trim()});}
 const earlier=[...new Map((snapshot?.changes||[]).filter(c=>c.kind==='answer').map(c=>[c.questionId!,c])).values()].filter(c=>!record?.questions.some(q=>q.id===c.questionId));
 return <main className={styles.root}><a href='/admin/p5-estimators'>Estimator administration</a><h1>P5 project review</h1><p>Staff qualification workspace. Review evidence, answer project questions and inspect preliminary estimates. This workspace does not send or publish estimates.</p>
  <form onSubmit={e=>{e.preventDefault();void load();}}><label htmlFor='project-id'>Saved project reference</label><input id='project-id' value={id} onChange={e=>setId(e.target.value)} disabled={locked} required/><button disabled={locked||!id.trim()}>Load project</button></form>
  {error&&<p role='alert' className={styles.error}>{error}</p>}{message&&<p role='status' aria-live='polite'>{message}</p>}{pendingChange&&<button onClick={()=>void save(pendingChange)} disabled={busy}>Retry the same save</button>}
  {snapshot&&<><p>Project {loadedId} · Saved revision {snapshot.draftRevision}{record?` · ${record.service}`:''}</p>{!current&&<p>The saved scope review is out of date or has not run. Prior prices are hidden until current information is reviewed.</p>}
   <div className={styles.actions}><button onClick={()=>void run('interpret')} disabled={locked}>Review current scope / resume</button><button onClick={()=>void run('price')} disabled={locked||!current||!record||record.questions.some(q=>q.priority==='blocking')}>Generate estimate / resume</button><button onClick={()=>void load()} disabled={locked}>Reload saved result</button></div>
   {problems.length>0&&<section><h2>Issues to resolve</h2><ul>{problems.map((p,i)=><li key={i}>{p.message}{p.ids.length>0&&<details><summary>Affected references</summary><code>{p.ids.join(', ')}</code></details>}</li>)}</ul></section>}
   {!!snapshot.attempts?.length&&<details><summary>Saved stage diagnostics</summary><p>Staff evidence only. Candidates and model reviews below are not accepted estimates. Attempts without revision metadata cannot establish current qualification.</p><pre>{JSON.stringify(snapshot.attempts,null,2)}</pre></details>}
   {record&&<><h2>Project scope</h2><p>{record.summary}</p>
    {current&&record.questions.length>0&&<section><h2>Project questions</h2>{record.questions.map(q=><form key={q.id} onSubmit={e=>{e.preventDefault();change(answers[q.id]||'',q.id);}}><label htmlFor={'answer-'+q.id}>{q.prompt}</label><p id={'reason-'+q.id}>{q.reason}</p>{q.options.length>0&&<div className={styles.actions}>{q.options.map(option=><button type='button' key={option} disabled={locked} onClick={()=>setAnswers({...answers,[q.id]:option})}>{option}</button>)}</div>}<textarea id={'answer-'+q.id} aria-describedby={'reason-'+q.id} rows={3} maxLength={10000} value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} disabled={locked} required/><button disabled={locked||!answers[q.id]?.trim()}>Save answer</button></form>)}</section>}
    <div className={styles.table}><table><caption>Work, responsibilities and exclusions</caption><thead><tr><th>Work</th><th>Status / responsibility</th><th>Quantity / basis</th></tr></thead><tbody>{record.requirements.map(r=>{const q=record.quantities.find(q=>q.id===r.quantityId);return <tr key={r.id}><td>{r.description}<small>{r.operation} · {r.component}</small></td><td>{r.status} · {r.responsibility}</td><td>{q?`${q.value??'Unknown'} ${q.unit??'(unit unresolved)'} · ${q.basis}`:'Supporting effort or no physical quantity'}{q?.assumption&&<small>{q.assumption}</small>}</td></tr>;})}</tbody></table></div>
    {current&&<section><h2>Revise the project</h2><form onSubmit={e=>{e.preventDefault();change(revision);}}><label htmlFor='scope-change'>What should change?</label><textarea id='scope-change' rows={4} maxLength={10000} value={revision} onChange={e=>setRevision(e.target.value)} disabled={locked} required/><button disabled={locked||!revision.trim()}>Save scope revision</button></form>{earlier.map(c=><details key={c.questionId}><summary>Correct an earlier answer: {c.prompt}</summary><p>Current saved answer: {c.response}</p><form onSubmit={e=>{e.preventDefault();change(answers[c.questionId!]||'',c.questionId!);}}><label htmlFor={'earlier-'+c.questionId}>Corrected answer</label><textarea id={'earlier-'+c.questionId} value={answers[c.questionId!]||''} onChange={e=>setAnswers({...answers,[c.questionId!]:e.target.value})} maxLength={10000} rows={3} disabled={locked} required/><button disabled={locked||!answers[c.questionId!]?.trim()}>Save corrected answer</button></form></details>)}</section>}
    {current&&snapshot.saved?.result?.status==='estimated'&&snapshot.saved.result.customer!==undefined&&<section><h2>Customer estimate preview</h2><div className={estimateStyles.root}><P5EstimateDetails result={snapshot.saved.result.customer}/></div></section>}
    <section><h2>Source evidence</h2>{record.sources.map(source=><details key={source.id}><summary>{source.name} · {source.status}</summary><p>{source.kind}</p><pre>{source.text}</pre></details>)}</section><details><summary>Saved answer and revision history</summary>{snapshot.changes.map(c=><article key={c.sequence}><h3>Revision {c.draftRevision}: {c.prompt}</h3><p>{c.response}</p></article>)}</details>
   </>}
  </>}
 </main>;
}
