import {atomicInstructionQuestions,textBenchTopChoices,cabinetQuestionField} from './atomicQuestions.ts';
import type {ScopeAnswers,ScopeExtraction,ScopeField} from './scope.ts';
import {alternativeOptions} from './quantityReconciliation.ts';

export interface InstructionAnswer {id:string;question:string;answer:string}
export interface InstructionPrompt {id:string;question:string;detail?:string;values?:string[];field?:ScopeField}
export const visitorQuestionText=(text:string)=>text
  .replace(/\b(?:previousAnswers|savedProjectDetails)\b/gi,'saved project details')
  .replace(/\b(?:submittedScope|projectDescription)\b/gi,'project description');
export const questionKey=(text:string)=>visitorQuestionText(text).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const answerBlock=(record:InstructionAnswer)=>`Question: ${record.question}\nAnswer: ${record.answer}`;

/** Remove only clarification blocks generated by this wizard, leaving typed scope notes intact. */
export function removeInstructionAnswerBlocks(text:string,history:InstructionAnswer[]=[]){
  if(!text.trim()||!history.length)return text;
  const generated=new Set(history.map(answerBlock));
  return text.split(/\n\s*\n/).filter(part=>!generated.has(part.trim())).join('\n\n').trim();
}
const serviceQuestion=(text:string)=>/which .*services|what .*remodel.*service|company.s scope|typical .*services|offered.*services|services.*offered|residential remodel|boise .*estimate|requested subset/i.test(text);

/** One question per card, including older extractions that stored paragraphs. */
export function instructionPrompts(extraction:ScopeExtraction|null,answers:ScopeAnswers):InstructionPrompt[]{
  const result:InstructionPrompt[]=[];
  for(const raw of extraction?.instructions?.questions||[]){
    for(const part of (raw.match(/[^?]+\??/g)||[]).flatMap(part=>atomicInstructionQuestions(part,answers,extraction?.conflicts))){
      const full=visitorQuestionText(part.replace(/\s+/g,' ').trim());if(!full)continue;
      // Filter each question separately so a legacy paragraph cannot lose a real scope decision.
      if(serviceQuestion(full))continue;
      const field=cabinetQuestionField(full);
      if(field&&answers[field]?.trim()&&!extraction?.conflicts.some(conflict=>conflict.field===field))continue;
      const id=questionKey(full);
      if(result.some(q=>q.id===id))continue;
      const question=full.length<=240?full:'What should we include for this part of your project?';
      const values=/labor.only/i.test(full)&&/materials.only/i.test(full)?['Labor only','Materials only','Labor and materials']:
        /include or exclude|include.*or.*exclude/i.test(full)?['Include it','Exclude it']:
        alternativeOptions(full,extraction?.takeoffs||[]);
      result.push({id,question,...(field?{field}:{}),...(question!==full?{detail:full}:{}),values:/^Who should install the /i.test(full)?['Include installation in this estimate','Owner handles installation']:values?.length?values:textBenchTopChoices(extraction,full)});
    }
  }
  return result;
}

/** Answers remain scope data for the pricing audit, with original pages intact. */
export function clarificationContext(extraction:ScopeExtraction,question:string,answer:string){
  return JSON.stringify({
    task:'Resolve only this answered scope question using the answer below. Return the complete updated instructions, preserving every unrelated inclusion, exclusion, responsibility, building and floor. Remove this question when answered. Never ask it again because a page was not reuploaded. This is a clarification of a document review already completed. Do not produce page records, takeoffs, or unreadable-file notes. If the answer is insufficient, return one short, specific follow-up explaining the missing decision.',
    previousInstructions:extraction.instructions,question,answer,
  });
}
