import {estimateSections,money,scopeBullets,type EstimateSection} from './presentation.ts';
import {ESTIMATOR_BRAND as brand} from './brand.ts';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function estimateEmail(id:string,record:any,admin:boolean){
 const result=record.customer, internal=record.internal||{};
 const sections:EstimateSection[]=[{title:result.range?`${money(result.range.low)} to ${money(result.range.high)}`:'Scope received for pricing review',text:result.message},...estimateSections(result)];
 if(admin){
  sections.unshift({title:'Internal estimate record',text:'Confidential. The internal attachment and financial breakdown are for the estimating team only.',rows:[['Reference',id],['Customer',record.contact?.name||'Not supplied'],['Email',record.contact?.email||'Not supplied'],['Phone',record.contact?.phone||'Not supplied']]});
  sections.push({title:'Internal financial breakdown',rows:[['Direct project cost',internal.directCost],['Contingency',internal.contingency],['Overhead recovery',internal.allocationDollars?.overhead],['Operating profit',internal.operatingProfit]].filter(([,v])=>typeof v==='number').map(([k,v])=>[String(k),money(Number(v))])});
  if(internal.warnings?.length)sections.push({title:'Pricing checks requiring attention',bullets:internal.warnings.map((w:any)=>w.message)});
 }
 sections.push({title:'Recommended next step',text:result.nextStep},{title:'Planning disclaimer',text:result.disclaimer});
 const text=[brand.name,admin?'CONFIDENTIAL INTERNAL ESTIMATE':'YOUR PROJECT PLANNING SUMMARY',`Reference: ${id}`,...sections.map(s=>[s.title.toUpperCase(),s.text,...(s.bullets||[]).map(x=>`• ${x}`),...(s.rows||[]).map(([k,v])=>`${k}\n  ${v}`)].filter(Boolean).join('\n\n')),`${brand.phone}\nhttps://${brand.domain}${brand.consultationPath}`,admin?'The complete administrative estimate is attached. Do not forward it to the customer.':'Your project summary is attached.'].join('\n\n');
 const html=`<!doctype html><html><body style="margin:0;background:#f2f0eb;color:#25332c;font-family:Arial,sans-serif"><main style="max-width:680px;margin:24px auto;background:#fff;padding:28px;overflow-wrap:anywhere"><p style="letter-spacing:2px;font-size:12px">${escape(brand.name)}</p><h1 style="font-size:28px;line-height:1.25;margin:12px 0 24px">${admin?'Internal estimate record':'Your project planning summary'}</h1><p style="font-size:12px">Reference ${escape(id)}</p>${sections.map(s=>`<section style="margin:28px 0;border-top:2px solid #c5cfc7;padding-top:16px"><h2 style="font-size:20px;line-height:1.4;margin:0 0 14px">${escape(s.title)}</h2>${s.text?`<p style="line-height:1.7;margin:0 0 16px;white-space:pre-line">${escape(s.text)}</p>`:''}${s.bullets?.length?`<ul style="padding-left:22px">${s.bullets.map(x=>`<li style="line-height:1.7;margin-bottom:12px">${escape(x)}</li>`).join('')}</ul>`:''}${(s.rows||[]).map(([k,v])=>`<div style="padding:14px 0;border-bottom:1px solid #e2e7e3"><h3 style="font-size:14px;margin:0 0 7px">${escape(k)}</h3><p style="line-height:1.7;margin:0;white-space:pre-line">${scopeBullets(v).map(part=>escape(part)).join('<br/><br/>')}</p></div>`).join('')}</section>`).join('')}<p style="line-height:1.7">${admin?'The complete administrative estimate is attached. Do not forward it to the customer.':'Your project summary is attached.'}</p><p><a href="https://${escape(brand.domain+brand.consultationPath)}">Schedule a consultation</a> · ${escape(brand.phone)}</p></main></body></html>`;
 return {text,html};
}
