import {ESTIMATOR_BRAND as brand} from './brand.ts';
import {INTAKE_SITES,INTAKE_RECIPIENTS} from './intakePolicy.ts';
import {intakeReference,type IntakeSnapshot} from './intakeContract.ts';
import {SCOPE_FIELDS} from './scope.ts';

const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export interface IntakeEmailFile {name:string;size:number;url?:string;attached?:boolean}
/** Only submitted fields and customer-visible conversation enter this projection.
 * Extraction, private notes, provider traces and internal costs never enter it. */
export function renderIntakeEmail(s:IntakeSnapshot,team:boolean,files:IntakeEmailFile[]){
 const site=INTAKE_SITES[s.currentSite],ref=intakeReference(s.projectId),accent=brand.id===s.currentSite?brand.accent:'#D0B496';
 const rows=[['Name',s.contact.name],['Email',s.contact.email],['Phone',s.contact.phone],['Preferred contact',s.contact.preferredContact],['Primary team',s.routing.teamName],['Supporting work',s.routing.supportingServices.map(x=>x.replaceAll('-',' ')).join(', ')],['Submitted through',INTAKE_SITES[s.originSite].name]];
 const answers=Object.entries(s.scope.answers).filter(([,v])=>v?.trim()).map(([k,v])=>[Object.hasOwn(SCOPE_FIELDS,k)?SCOPE_FIELDS[k as keyof typeof SCOPE_FIELDS].label:k,v||'']);
 const details=[['Desired outcome',s.details.desiredOutcome],['Project context',s.details.workContext],['Budget',s.details.budget]].filter(([,v])=>v);
 const next='The team will review your scope and files before preparing an estimate. We will use your preferred contact method if more information or a site visit is needed. This is a project request, not a priced estimate.';
 const fileNote=files.length?'Every saved file is listed below. Attached originals are identified individually. Private download links expire after 14 days; keep them private. If a link expires, contact the team for help.':'No files were submitted.';
 const fileText=files.map(f=>`${f.name} (${f.size.toLocaleString('en-US')} bytes)${f.attached?': attached original':''}${f.url?`\nPrivate download: ${f.url}`:': saved with your request; delivery access is pending'}`).join('\n');
 const conversation=s.details.transcript.map(m=>`${m.role==='user'?'You':'Project assistant'}${m.label?` · ${m.label}`:''}: ${m.text}${m.caption?`\n${m.caption}`:''}${m.files?.length?`\nFiles: ${m.files.join(', ')}`:''}`).join('\n\n');
 const title=team?'New project request':'Your project request is saved';
 const text=[site.name,title,`${ref} · Revision ${s.revision}`,`Saved: ${s.savedAt}`,'',...rows.map(([k,v])=>`${k}: ${v||'Not provided'}`),'','PROJECT SCOPE',s.scope.text||'See submitted answers and files.','',...answers.concat(details).map(([k,v])=>`${k}: ${v}`),'','FILES',fileNote,fileText,...(s.unresolved.length?['','DETAILS TO CONFIRM',...s.unresolved]:[]),...(conversation?['','YOUR SUBMITTED CONVERSATION',conversation]:[]),'','WHAT HAPPENS NEXT',next,`Contact ${INTAKE_RECIPIENTS[s.currentSite]} about this request.`,...(!s.contact.email?['No customer confirmation email was requested; follow up using the supplied phone number.']:[])].join('\n');
 const paragraph=(v:string)=>`<p style="margin:0 0 16px;white-space:pre-wrap;overflow-wrap:anywhere">${escape(v)}</p>`;
 const heading=(v:string)=>`<h2 style="font-size:19px;margin:28px 0 12px;color:#2C302F">${escape(v)}</h2>`;
 const table=(items:string[][])=>`<table role="presentation" style="width:100%;border-collapse:collapse">${items.map(([k,v])=>`<tr><td style="padding:10px 12px 10px 0;border-bottom:1px solid #e2e4df;vertical-align:top;width:34%;color:#565D58">${escape(k)}</td><td style="padding:10px 0;border-bottom:1px solid #e2e4df;white-space:pre-wrap;overflow-wrap:anywhere">${escape(v||'Not provided')}</td></tr>`).join('')}</table>`;
 const logo=brand.id===s.currentSite?`<img src="https://${site.domain}${escape(brand.logo)}" alt="${escape(site.name)}" width="210" style="display:block;max-width:100%;height:auto;margin-bottom:22px"/>`:'';
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${escape(site.name)} · ${escape(ref)}</title></head><body style="margin:0;background:#F7F5F3;color:#2C302F;font-family:Arial,Helvetica,sans-serif;line-height:1.6"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:24px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;margin:auto;background:#fff;border-top:6px solid ${accent}"><tr><td style="padding:32px 24px">${logo}<p style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;margin:0">${escape(site.name)} · ${escape(ref)}</p><h1 style="font-size:30px;line-height:1.2;margin:12px 0 16px">${title}</h1>${paragraph(team?'A submitted project is ready for your review.':`Thank you${s.contact.name?`, ${s.contact.name}`:''}. Here is a copy of the project you sent us.`)}${paragraph(`Revision ${s.revision} · Saved ${s.savedAt}`)}${heading('Project at a glance')}${table(rows)}${heading('Your project scope')}${paragraph(s.scope.text||'See submitted answers and files.')}${table(answers.concat(details))}${heading(`Files (${files.length})`)}${paragraph(fileNote)}${files.map(f=>`<p style="padding:12px;background:#F7F5F3;overflow-wrap:anywhere"><strong>${escape(f.name)}</strong><br/>${f.size.toLocaleString('en-US')} bytes · ${f.attached?'Original attached':'Saved original'}${f.url?`<br/><a href="${escape(f.url)}" style="color:#2C302F;text-decoration:underline">Download original privately</a>`:'<br/>Delivery access is pending.'}</p>`).join('')}${s.unresolved.length?heading('Details to confirm')+s.unresolved.map(paragraph).join(''):''}${conversation?heading('Your submitted conversation')+paragraph(conversation):''}${heading('What happens next')}${paragraph(next)}${!s.contact.email?paragraph('Phone-only inquiry: no customer confirmation email was requested.'):''}<p style="border-top:1px solid #e2e4df;padding-top:20px;margin-top:28px"><strong>${escape(site.name)}</strong><br/><a style="color:#2C302F" href="mailto:${INTAKE_RECIPIENTS[s.currentSite]}">${INTAKE_RECIPIENTS[s.currentSite]}</a><br/><a style="color:#2C302F" href="https://${site.domain}">${site.domain}</a></p></td></tr></table></td></tr></table></body></html>`;
 return {text,html,subject:`${site.name}: ${team?'Project request':'Your project request'} ${ref} · revision ${s.revision}`};
}
