/**
 * Words that name the same thing on a job site.
 *
 * Scopes, plans and RE-10s are written by homeowners, agents, inspectors and architects, and
 * almost never in the price book's own words: an inspector writes "receptacle" where the book says
 * "outlet", a homeowner writes "spigot" for a hose bib and "can lights" for recessed lights. The
 * catalog shown to the mapping stage is chosen by the words a task shares with each line, so every
 * word in a group below stands in for all of the others. The final match is still made by the
 * model reading the line; this only makes sure the right line is on the table for it to read.
 *
 * Groups are deliberately narrow: each is one thing, not a trade. "Plumbing" is not a synonym for
 * "toilet", or every plumbing task would pull every plumbing line and crowd out the right one.
 */
export const TRADE_SYNONYMS:readonly (readonly string[])[]=[
  // Whole projects, so a complete-assembly line (Division 90) is offered for a whole-job task.
  ['new home','new house','new residence','new dwelling','new single family','new single-family','custom home','ground up','ground-up','new build','new-build','new construction','new-construction','construct a home','build a home','construct one new','residence construction'],
  ['whole home','whole house','whole-home','whole-house','entire home','entire house','gut remodel','full renovation','full remodel'],
  ['detached garage','shop building','detached shop'],
  // Electrical
  ['outlet','receptacle','plug','socket','duplex'],
  ['gfci','gfi','ground fault'],
  ['afci','arc fault'],
  ['switch','dimmer','toggle'],
  ['breaker','circuit breaker','fuse'],
  ['electrical panel','load center','service panel','breaker box','fuse box','main panel'],
  ['recessed','can light','pot light','downlight','high hat'],
  ['light fixture','luminaire','lamp','light fitting'],
  ['ceiling fan','paddle fan'],
  ['smoke','smoke alarm','smoke detector','co alarm','carbon monoxide'],
  ['wire','wiring','romex','cable','conductor'],
  ['grounding','bonding','ungrounded','open ground'],
  ['doorbell','door chime'],
  // Plumbing
  ['hose bib','sillcock','spigot','hose bibb','exterior faucet','outdoor faucet','frost free','frostfree'],
  ['trap','p trap','ptrap','s trap','drain trap'],
  ['toilet','commode','water closet','wc'],
  ['faucet','mixer tap','kitchen faucet'],
  ['lavatory','lav','bathroom sink','vanity sink'],
  ['garbage disposal','disposer','food waste disposer'],
  ['water heater','hot water heater','hot water tank','hwh','tank heater'],
  ['tankless','on demand'],
  ['tpr','relief valve','temperature pressure relief','t p valve'],
  ['shutoff','shut off','angle stop','stop valve','supply stop'],
  ['supply line','supply hose','water line'],
  ['plumbing vent','vent stack','vent pipe'],
  ['vacuum breaker','backflow preventer','anti siphon','antisiphon'],
  ['sump','sump pump'],
  ['sewer','sewer line','lateral','main line'],
  ['leak','drip','dripping','leaking','seep'],
  ['shower valve','mixing valve','diverter','cartridge'],
  ['water softener','softener','conditioner'],
  // HVAC and ventilation
  ['furnace','forced air','gas furnace'],
  ['air conditioner','air conditioning','condenser','ac unit','central air'],
  ['heat pump','mini split','ductless'],
  ['exhaust fan','bath fan','vent fan','bathroom fan','ventilation fan'],
  ['dryer vent','dryer duct','dryer exhaust'],
  ['duct','ductwork','duct work','plenum'],
  ['thermostat','t stat','tstat'],
  ['filter','air filter'],
  // Roofing and exterior
  ['shingle','shingles','roofing','reroof','re roof'],
  ['pipe boot','vent boot','roof jack','boot','plumbing vent flashing','rubber boot','neoprene boot'],
  ['flashing','step flashing','counter flashing','drip edge'],
  ['gutter','gutters','eavestrough','rain gutter'],
  ['downspout','down spout','leader','rain leader'],
  ['soffit','eave','overhang'],
  ['fascia','fascia board'],
  ['chimney','flue','chimney crown','chimney cap','chimney chase'],
  ['skylight','roof window'],
  ['siding','cladding','lap siding','hardie','fiber cement'],
  ['stucco','eifs','synthetic stucco'],
  ['caulk','caulking','sealant'],
  // Structure, crawl space and insulation
  ['crawlspace','crawl space','crawl','underfloor'],
  ['vapor barrier','moisture barrier','vapour barrier','visqueen','ground cover','poly sheeting'],
  ['insulation','batt','batts','blown in','loose fill','fiberglass insulation'],
  ['joist','floor joist','rafter','truss'],
  ['subfloor','sub floor','floor decking'],
  ['beam','header','lintel'],
  ['foundation','footing','stem wall'],
  ['sill plate','mudsill','mud sill'],
  ['rot','dry rot','decay','wood rot','rotted'],
  ['termite','wood destroying','pest'],
  ['grading','slope','drainage','regrade'],
  // Interior finishes
  ['drywall','sheetrock','gypsum','wallboard','plasterboard','gyp board'],
  ['patch','hole','ding'],
  ['texture','knockdown','orange peel','skim'],
  ['paint','painting','repaint','coating'],
  ['trim','baseboard','base board','casing','molding','moulding'],
  ['crown molding','crown moulding'],
  ['lvp','luxury vinyl plank','vinyl plank','luxury vinyl'],
  ['hardwood','wood floor','oak floor','engineered wood'],
  ['carpet','carpeting','wall to wall'],
  ['tile','ceramic','porcelain'],
  ['grout','regrout'],
  ['backsplash','back splash'],
  ['countertop','counter top','countertops','worktop','benchtop'],
  ['quartz','engineered stone'],
  ['cabinet','cabinets','cabinetry','casework','cupboard'],
  ['vanity','bathroom cabinet'],
  ['shower','shower stall','shower surround'],
  ['tub','bathtub','bath tub'],
  ['door','doors','interior door'],
  ['entry door','front door','exterior door'],
  ['window','windows','glazing','sash'],
  ['screen','window screen'],
  ['weatherstrip','weatherstripping','weather strip','door sweep','threshold'],
  ['handrail','hand rail','railing','guardrail','guard rail','banister'],
  ['stair','stairs','steps','staircase','stairway','tread','riser'],
  ['closet','wardrobe','shelving'],
  // Appliances and site
  ['dishwasher','dish washer'],
  ['stove','oven','cooktop','kitchen range','gas range','electric range'],
  ['refrigerator','fridge'],
  ['microwave','otr microwave'],
  ['range hood','vent hood','hood'],
  ['washer','washing machine','laundry'],
  ['sprinkler','irrigation','lawn sprinkler'],
  ['fence','fencing'],
  ['deck','decking','patio deck'],
  ['concrete','cement','flatwork','concrete slab'],
  ['driveway','drive way'],
  ['landscaping','landscape','yard'],
  ['fireplace','hearth','firebox','fireplace insert'],
  ['glass door','fireplace door','fireplace screen'],
  ['igniter','ignitor','ignition','pilot','thermocouple'],
  ['damper','flue damper'],
  // Work and disposal
  ['demolition','demo','tear out','teardown','remove and dispose'],
  ['haul','haul off','dump','debris','junk'],
  ['garage door','overhead door','roll up door'],
  ['opener','garage door opener'],
];
