export const FIELDS = {
  estimatingInstructions: {label: "Custom estimating instructions", kind: "text"},
  service: { label: "Project type", kind: "choice", options: ["handyman", "re10", "cabinet-product", "cabinet-install", "kitchen", "bathroom", "whole-home", "addition", "adu", "new-construction", "change-order", "rush"] },
  location: { label: "City, ZIP code, county or general location", kind: "text" },
  address: { label: "Property address (optional)", kind: "text" },
  sqft: { label: "Project area in square feet", kind: "number" },
  garageIncluded: { label: "Garage in this project", kind: "choice", options: ["yes", "no"] },
  garageSqft: { label: "Garage area in square feet", kind: "number" },
  coveredOutdoorSqft: { label: "Covered outdoor area in square feet", kind: "number" },
  cabinetTallLf: { label: "Tall cabinet run in linear feet", kind: "number" },
  cabinetConstruction: { label: "Cabinet construction and hardware specification", kind: "text" },
  length: { label: "Length in feet", kind: "number" },
  width: { label: "Width in feet", kind: "number" },
  rooms: { label: "Number of rooms", kind: "number" },
  bathrooms: { label: "Number of bathrooms", kind: "number" },
  stories: { label: "Number of stories", kind: "number" },
  cabinetBaseLf: { label: "Base cabinet run in linear feet", kind: "number" },
  cabinetUpperLf: { label: "Upper cabinet run in linear feet", kind: "number" },
  cabinetRoom: { label: "Cabinet room", kind: "choice", options: ["kitchen", "bathroom", "laundry", "mudroom", "home-office", "entertainment", "built-ins", "pantry"] },
  finish: { label: "Finish level", kind: "choice", options: ["refresh", "mid-range", "high-end", "luxury"] },
  materials: { label: "Materials and finishes", kind: "text" },
  fixtures: { label: "Fixtures", kind: "text" },
  appliances: { label: "Appliances and responsibilities", kind: "text" },
  demolition: { label: "Demolition", kind: "text" },
  structural: { label: "Structural work", kind: "text" },
  mechanical: { label: "Heating, cooling and ventilation", kind: "text" },
  electrical: { label: "Electrical work", kind: "text" },
  plumbing: { label: "Plumbing work", kind: "text" },
  site: { label: "Site conditions, soil and slope", kind: "text" },
  access: { label: "Access and occupied-home constraints", kind: "text" },
  allowances: { label: "Allowances and selection deadlines", kind: "text" },
  exclusions: { label: "Excluded work", kind: "text" },
  alternates: { label: "Alternates", kind: "text" },
  ownerSupplied: { label: "Owner-supplied items and responsibilities", kind: "text" },
  permits: { label: "Permits and inspections", kind: "text" },
  engineering: { label: "Engineering and design", kind: "text" },
  utilities: { label: "Utilities and connections", kind: "text" },
  schedule: { label: "Requested schedule", kind: "text" },
  urgency: { label: "Timing", kind: "choice", options: ["standard", "priority", "emergency"] },
  complexity: { label: "Project complexity", kind: "choice", options: ["standard", "complex"] },
  phasing: { label: "Project phasing", kind: "text" },
  flooringSqft: { label: "Flooring area in square feet", kind: "number" },
  tileSqft: { label: "Tile area in square feet", kind: "number" },
  countertopSqft: { label: "Countertop area in square feet", kind: "number" },
  demolitionSqft: { label: "Demolition area in square feet", kind: "number" },
  fixtureCount: { label: "Number of fixtures", kind: "number" },
  laborHours: { label: "Estimated labor hours", kind: "number" },
  trimLf: { label: "Trim or baseboard length in feet", kind: "number" },
  projectMonths: { label: "Estimated construction duration in months", kind: "number" },
  installation: { label: "Installation work and responsibilities", kind: "text" },
  taskList: { label: "Tasks and quantities", kind: "text" },
  otherDetails: { label: "Other scope details", kind: "text" },
};
