// Real site modules, signed service handler and SQL; fake provider, zero sockets.
import './offline-network-guard.cjs';
import assert from 'node:assert/strict';
import {mkdtemp,cp,writeFile,rm,mkdir} from 'node:fs/promises';
import {randomUUID,randomBytes} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {Readable} from 'node:stream';
import path from 'node:path';
import {Store} from '../services/document-service/src/store.mjs';
import {Reader} from '../services/document-service/src/provider.mjs';
import {makeServer} from '../services/document-service/src/server.mjs';
import {signedHeaders} from '../services/document-service/src/core.mjs';
import {QA_MODEL} from '../services/document-service/src/qa-budget.mjs';
for(const key of Object.keys(process.env))if(key.startsWith('AI_INTEGRATIONS_'))delete process.env[key];
const tenant='p5homeco.com',secret='offline-synthetic-signing-key-not-a-secret';
Object.assign(process.env,{DATABASE_URL:'',P5_ESTIMATOR_PROVIDER:'anthropic',ANTHROPIC_API_KEY:'fake-no-provider-key',OPENAI_API_KEY:'fake-no-provider-key',P5_DOCUMENT_SERVICE_MODE:'remote',P5_DOCUMENT_SERVICE_URL:'https://qa-ledger.invalid',P5_DOCUMENT_SERVICE_TENANT:tenant,P5_DOCUMENT_SERVICE_KEY:secret});
await mkdir('node_modules/.cache',{recursive:true});const dir=await mkdtemp(path.join(process.cwd(),'node_modules/.cache/p5-paid-'));
let db:any,server:any,escaped=0,providerCalls=0,brokerCalls=0;
try{
 await cp('lib/p5',dir,{recursive:true});
 await writeFile(path.join(dir,'database.ts'),`import {PGlite} from '@electric-sql/pglite';export const database=new PGlite();export async function query(s:string,v:unknown[]=[]){return (await database.query(s,v)).rows;}export async function transaction<T>(fn:any){return database.transaction(tx=>fn(async(s:string,v:unknown[]=[])=> (await tx.query(s,v)).rows));}`);
 await writeFile(path.join(dir,'deliveryAdapter.ts'),`export const EMAIL_SUPPORTS_IDEMPOTENCY=true;export async function adminRecipients(){return ['admin@example.invalid'];}export async function sendEmail(){throw Error('Unexpected QA email');}export async function syncCrm(){throw Error('Unexpected QA CRM');}`);
 const load=(name:string)=>import(pathToFileURL(path.join(dir,name+'.ts')).href);
 db=(await load('database')).database;
 const query=async(s:string,v?:unknown[])=>{if(v===undefined&&s.includes('CREATE TABLE')){await db.exec(s);return {rows:[],rowCount:0};}const r=await db.query(s,v);return {...r,rowCount:r.affectedRows??r.rows.length};};
 const config={tenants:{[tenant]:secret},provider:'anthropic',model:QA_MODEL,verifyModel:QA_MODEL,key:'fake-only',slots:2,rpm:100,tpm:1000000,callMs:20000,maxOutput:1000,reviewMaxOutput:1000,maxBytes:250*1024*1024,maxPages:250};
 const remote=new Store({query},config);let tail=Promise.resolve();
 remote.transaction=(fn:any)=>{const r=tail.then(()=>db.transaction((tx:any)=>fn({query:async(s:string,v?:unknown[])=>{const q=await tx.query(s,v);return {...q,rowCount:q.affectedRows??q.rows.length};}})));tail=r.catch(()=>{});return r;};
 await remote.init();
 remote.qa.request=async(url:any,init:any)=>{assert.equal(url,'https://api.anthropic.com/v1/messages');providerCalls++;const wire=JSON.parse(init.body);assert.equal(wire.service_tier,'standard_only');assert.equal(wire.stream,false);const name=wire.tools?.[0]?.name;return Response.json({id:'msg_'+providerCalls,model:QA_MODEL,stop_reason:name?'tool_use':'end_turn',usage:{input_tokens:100,output_tokens:20,cache_creation_input_tokens:0,cache_read_input_tokens:0},content:name?[{type:'tool_use',id:'tool_test',name,input:name==='record_shortlist'?{tasks:[{id:'t1',codes:['PB-X']}]}:name==='record_estimate'?{tasks:[{id:'t1',description:'Cabinet supply',evidence:'Ten feet requested'}],issues:[]}:{value:'accepted'}}]:[{type:'text',text:'accepted'}]},{headers:{'request-id':'req_'+providerCalls}});};
 server=makeServer(remote,{},config);
 const serve=(url:string,init:any)=>new Promise<Response>((resolve,reject)=>{const req:any=Readable.from(init?.body?[Buffer.from(init.body)]:[]);req.method=init.method||'GET';req.url=new URL(url).pathname;req.headers=Object.fromEntries(new Headers(init.headers));const res:any={writableEnded:false,destroyed:false,status:200,headers:{},writeHead(status:number,headers:any){this.status=status;this.headers=headers;},setHeader(k:string,v:string){this.headers[k]=v;},end(value:string){this.writableEnded=true;resolve(new Response(value,{status:this.status,headers:this.headers}));}};try{server.emit('request',req,res);}catch(e){reject(e);}});
 globalThis.fetch=async(input:any,init:any)=>{const url=String(input);if(!url.startsWith('https://qa-ledger.invalid/v1/projects/qa-paid-')){escaped++;throw Error('Unexpected network boundary '+new URL(url).origin);}brokerCalls++;assert.equal(new Headers(init?.headers).has('x-api-key'),false,'provider key is never forwarded');return serve(url,init);};
 const site=await load('store'),qa=await load('qaPaid'),client=await load('estimatorModelClient'),shortlist=await load('bookShortlist'),review=await load('reviewRequest'),draftEndpoint=await load('draftEndpoint');
 const id=randomUUID(),key=randomBytes(32).toString('hex'),project='qa-paid-'+id;
 const payload={text:'[QA] Install three owner supplied passage levers.',answers:{service:'handyman',location:'Boise'},contact:{name:'[QA] Paid bounded acceptance',email:'',phone:''},extraction:null,reviewed:null};
 await site.ensureSchema();
 await db.exec(`CREATE FUNCTION qa_atomic_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.work_key='qa-bounded-provider-v1' THEN RAISE EXCEPTION 'injected atomic marker failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER qa_atomic_fault BEFORE INSERT ON p5_estimator_work FOR EACH ROW EXECUTE FUNCTION qa_atomic_fault();`);
 await assert.rejects(site.saveDraft(id,key,'p5',payload,0,'bounded-paid'),/atomic marker failure/);assert.equal((await db.query('SELECT id FROM p5_estimator_drafts WHERE id=$1',[id])).rows.length,0);
 await db.exec('DROP TRIGGER qa_atomic_fault ON p5_estimator_work');await site.saveDraft(id,key,'p5',payload,0,'bounded-paid');await remote.qa.provision([{tenant,project}]);
 const run=(fn:any)=>qa.withQaPaidDraft(id,fn),request={max_tokens:1000,messages:[{role:'user',content:'Exact synthetic test input'}],tools:[{name:'record_test',input_schema:{type:'object',properties:{value:{type:'string'}},required:['value']}}],tool_choice:{type:'tool',name:'record_test'}};
 const call=()=>run(()=>client.createEstimatorModelClient().messages.create(request));
 await assert.rejects(call(),/review-required/);assert.equal(providerCalls,0);
 let ordinal=0;
 const permitLatest=async()=>{const [intent]=(await db.query('SELECT request_hash FROM p5ds_qa_intents ORDER BY created_at DESC LIMIT 1')).rows;await remote.qa.permit(intent.request_hash,'offline-review-'+(++ordinal),'Offline exact request review; fake provider only, no real dispatch.');};
 await permitLatest();assert.equal((await call()).model,QA_MODEL);assert.equal(providerCalls,1);await call();assert.equal(providerCalls,1,'reopen reuses retained paid response');
 await assert.rejects(run(()=>qa.withQaPaidDraft(randomUUID(),async()=>{})),/identity changed/);
 assert.equal(await run(()=>qa.qaDocumentProject(id)),project);assert.equal(await qa.qaDocumentProject(id),id);
 const select=()=>run(()=>shortlist.shortlistBook([{id:'t1',description:'Door lever'}],[{code:'PB-X',description:'Door hardware',unit:'EA'}]));
 await assert.rejects(select(),/review-required/);await permitLatest();assert.deepEqual([...(await select())],[['t1',['PB-X']]]);assert.equal(providerCalls,2);
 const reader=new Reader(config,remote,async()=>{escaped++;throw Error('Reader escaped QA ledger');});
 const job={id:'qa-native-read',tenant,project,kind:'read',attempts:1};const schema={type:'object',properties:{value:{type:'string'}},required:['value'],additionalProperties:false};
 const read=()=>reader.call(job,'Read original source',{pages:[]},[],schema,AbortSignal.timeout(20000));
 await assert.rejects(read(),/review-required/);await permitLatest();assert.deepEqual(await read(),{value:'accepted'});await read();assert.equal(providerCalls,3);
 await assert.rejects(reader.call({...job,project:'qa-paid-'+randomUUID()},'Read',{},[],schema,AbortSignal.timeout(20000)),/binding-required/);assert.equal(providerCalls,3);
 const badPath='/v1/projects/'+project+'/qa-provider',badBody=Buffer.from(JSON.stringify({boundary:'bad',body:{model:QA_MODEL,max_tokens:1000,messages:[{role:'user',content:'x'}]}}));
 const denied=await serve('https://qa-ledger.invalid'+badPath,{method:'POST',headers:signedHeaders('wrong-secret', 'POST',badPath,tenant,badBody),body:badBody});assert.equal(denied.status,401);
 let ordinary=0;await qa.qaProviderFetch(async()=>{ordinary++;return Response.json({ok:true});},'https://ordinary-provider.invalid',{method:'POST'});assert.equal(ordinary,1);
 const req=(route:string,body:any)=>new Request('https://p5homeco.com/api/p5-estimator/'+route,{method:route==='draft'?'PUT':'POST',headers:{origin:'https://p5homeco.com','content-type':'application/json','x-p5-draft-id':id,'x-p5-draft-key':key},body:JSON.stringify(body)});
 assert.equal((await review.requestProjectReview(req('review',{name:'QA',email:'nobody@example.invalid'}))).status,422);
 assert.equal((await draftEndpoint.putDraft(req('draft',{...payload,contact:{name:'Changed',email:'nobody@example.invalid',phone:''},revision:1}))).status,422);

 // Real work entry points must establish context themselves, not via run().
 const analysis=await load('analysisWork'),pricing=await load('pricingWork'),planning=await load('planningBooks');
 const savedDraft=await site.readDraft(id,key),beforeEntryCalls=providerCalls;
 for(let n=0;n<4;n++)await assert.rejects(analysis.advanceAnalysis(savedDraft,payload.text,payload.answers),/review-required/);
 assert.equal(providerCalls,beforeEntryCalls);
 const date=new Date(),stamp=date.toISOString();
 const configBook=planning.createPlanningConfiguration({version:planning.PLANNING_MODEL_VERSION,source:'Synthetic only',authorizedBy:'Offline test',importedAt:stamp,rates:['03-17-01-M','03-17-01-L','03-19-02-M','03-19-02-L','03-15-02-M','03-15-02-L','03-16-01-M','03-16-01-L','03-14-01-M','03-14-01-L','03-04-01','03-04-02','03-04-03','03-04-04','03-04-05','03-05-02-M','03-05-02-L','REF-GENERAL-HOUR','REF-PLUMBING-HOUR','REF-ELECTRICAL-HOUR'].map(code=>({code,description:'Synthetic cabinetry',type:code.endsWith('-M')?'Material':'Labor',unit:code.includes('HOUR')?'HR':'LF',amount:100,source:'Synthetic test',basis:'owner-average-cost'}))});
 const scope={text:'Supply ten feet of cabinetry.',answers:{service:'cabinet-product',cabinetBaseLf:'10',cabinetUpperLf:'0',cabinetTallLf:'0',location:'Boise'},extraction:null,uploads:[],reviewedAt:stamp,corrections:[]};
 const price=()=>pricing.priceSavedScope(id,scope,configBook,date,Date.now()+30000);
 for(let n=0;n<5;n++)await assert.rejects(price(),/review-required/);
 assert.equal(providerCalls,beforeEntryCalls);
 const workRows=await db.query('SELECT payload FROM p5_estimator_work WHERE draft_id=$1 AND work_key=$2',[id,pricing.pricingWorkKey(scope,configBook,date)]);
 assert.ok(Object.values(workRows.rows[0].payload.requests).every((r:any)=>r.attempt===0&&r.failures.length===0),'review holds do not exhaust attempts');
 await permitLatest();await assert.rejects(price(),/review-required/);assert.equal(providerCalls,beforeEntryCalls+1,'inventory resumes once then shortlist awaits separate review');
 const [shortIntent]=(await db.query('SELECT request FROM p5ds_qa_intents ORDER BY created_at DESC LIMIT 1')).rows;
 assert.equal(shortIntent.request.tools[0].name,'record_shortlist','real pricing retains QA context into shortlist');
 assert.equal((await db.query('SELECT * FROM p5_estimator_policy')).rows.length,0,'QA cannot mutate customer pricing policy');
 const evidence=await load('projectPageEvidence'),documents=await load('documentServiceClient');
 const sha='a'.repeat(64),documentId=documents.remoteDocumentId(tenant,project,sha),upload={id:randomUUID(),name:'QA source.pdf',status:'stored',type:'application/pdf',size:100,sha256:sha};
 let evidenceRequests=0;const base={version:'p5-page-evidence-v2',id:documentId,project,sha256:sha,name:upload.name,state:'complete',revision:'fixture-v1',pageCount:1};
 const pageResult=await run(()=>evidence.loadProjectPageEvidence({id,brand:'p5',uploads:[upload]},{cache:{read:async()=>undefined,write:async()=>{}},request:async(input:any)=>{evidenceRequests++;const u=new URL(String(input));assert.ok(u.pathname.includes('/projects/'+project+'/documents/'+documentId+'/evidence'));return Response.json(u.search?{...base,page:{number:1,native:{text:'Original fixture',textQuality:null,kind:'text',width:100,height:100,spanCoordinates:null,spans:[]},readerObservation:null}}:{...base,complete:true,pages:[{page:1,status:'read',notes:[]}]});}}));
 assert.equal(evidenceRequests,2);assert.equal(pageResult.documents[0].pages[0].native.text,'Original fixture');

 assert.equal(escaped,0);assert.ok(brokerCalls>=5);console.log('PASS: atomic paid marker; authentic signed broker; retained client and shortlist; real Reader.call; immutable identity; replay; wrong auth/unbound holds; no contacts; ordinary transport preserved; zero real network.');
}finally{if(db)await db.close();await rm(dir,{recursive:true,force:true});}
