import assert from 'node:assert/strict';
import {mkdtemp,cp,writeFile,readFile,mkdir} from 'node:fs/promises';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {createRequire} from 'node:module';
const ExcelJS=createRequire(path.join(process.cwd(),'package.json'))('exceljs');
const root=process.cwd();await mkdir('node_modules/.cache',{recursive:true});
const dir=await mkdtemp(path.join(root,'node_modules/.cache/adversarial-upload-'));
await cp('lib/p5',dir,{recursive:true});
await writeFile(path.join(dir,'database.ts'),`import {PGlite} from '@electric-sql/pglite';export const database=new PGlite();export async function query(s:string,v:unknown[]=[]){return (await database.query(s,v)).rows;}`);
await writeFile(path.join(dir,'storageFixture.ts'),`export const objects=new Map<string,Buffer>();export const state={failPart:false,failFinish:false,delay:0,failAfterPersist:false,sourceErrorOnly:false,beforeCommit:null as any};export class Client{async uploadFromBytes(k:string,b:Buffer){if(state.failPart)return {ok:false};objects.set(k,Buffer.from(b));return {ok:true};}async downloadAsBytes(k:string){return objects.has(k)?{ok:true,value:[objects.get(k)]}:{ok:false};}async uploadFromStream(k:string,s:any){if(state.sourceErrorOnly)return new Promise<void>(resolve=>{s.on('data',()=>{});s.on('end',resolve);});const parts=[];for await(const part of s)parts.push(part);if(state.delay)await new Promise(r=>setTimeout(r,state.delay));if(state.beforeCommit)await state.beforeCommit();if(state.failFinish)throw Error('synthetic final storage failure');objects.set(k,Buffer.concat(parts));if(state.failAfterPersist)throw Error('synthetic acknowledgement loss');}async delete(k:string){objects.delete(k);return {ok:true};}}`);
for(const name of ['objectStorage','resumableUpload']){const f=path.join(dir,name+'.ts');await writeFile(f,(await readFile(f,'utf8')).replace(/from ['"]@replit\/object-storage['"]/g,"from './storageFixture'"));}
globalThis.fetch=async()=>{throw Error('External network forbidden by test');};
process.env.P5_OBJECT_STORAGE_ENABLED='true';
const mod=(n:string)=>import(pathToFileURL(path.join(dir,n+'.ts')).href);
const store=await mod('store'),db=await mod('database'),api=await mod('resumableUpload'),fixture=await mod('storageFixture'),scope=await mod('scope');
const sha=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex');
const rows:any[]=[];
async function draft(){const id=randomUUID(),key=randomBytes(32).toString('hex');await store.saveDraft(id,key,'test',{text:'Synthetic QA',answers:{},extraction:null,reviewed:null,contact:{name:'',email:'',phone:''}},0);return {id,key};}
function request(d:any,digest:string,action:string,body:BodyInit='',extra='',headers:any={}){return api.postUpload(new Request('https://test.local/api/p5-estimator/upload?action='+action+'&sha256='+digest+extra,{method:'POST',headers:{'x-p5-draft-id':d.id,'x-p5-draft-key':d.key,...headers},body}));}
async function start(d:any,b:Buffer,name='scope.txt',digest=sha(b)){const r=await request(d,digest,'start',JSON.stringify({name,size:b.length}));assert.equal(r.status,200);return digest;}
async function part(d:any,b:Buffer,digest=sha(b)){return request(d,digest,'part',new Uint8Array(b),'&part=0&checksum='+sha(b));}
async function count(d:any){return (await store.readDraft(d.id,d.key)).uploads.length;}
async function test(name:string,fn:()=>Promise<any>){try{const details=await fn();rows.push({name,passed:true,details});}catch(e:any){rows.push({name,passed:false,error:e.message});}console.log(JSON.stringify(rows.at(-1)));}
await test('file size boundary rejects zero negative fractional and over-250MiB',async()=>{const d=await draft();for(const size of [0,-1,1.5,scope.SCOPE_FILE_LIMIT+1])assert.equal((await request(d,sha(String(size)),'start',JSON.stringify({name:'x.pdf',size}))).status,413);assert.equal((await request(d,sha('max'),'start',JSON.stringify({name:'max.pdf',size:scope.SCOPE_FILE_LIMIT}))).status,200);});
await test('pending transfers enforce 1GiB total without allocating large files',async()=>{const d=await draft();for(let n=0;n<4;n++)assert.equal((await request(d,sha(String(n)),'start',JSON.stringify({name:n+'.pdf',size:scope.SCOPE_FILE_LIMIT}))).status,200);assert.equal((await request(d,sha('remainder'),'start',JSON.stringify({name:'remainder.pdf',size:scope.SCOPE_BATCH_LIMIT-4*scope.SCOPE_FILE_LIMIT}))).status,200);assert.equal((await request(d,sha('over'),'start',JSON.stringify({name:'over.pdf',size:1}))).status,413);});
await test('pending transfer count rejects file 51',async()=>{const d=await draft();for(let n=0;n<50;n++)assert.equal((await request(d,sha(String(n)),'start',JSON.stringify({name:n+'.txt',size:1}))).status,200);assert.equal((await request(d,sha('over'),'start',JSON.stringify({name:'over.txt',size:1}))).status,413);});
await test('two concurrent admissions at file-count boundary cannot overbook',async()=>{const d=await draft();for(let n=0;n<49;n++)await start(d,Buffer.from(String(n)));const result=await Promise.all([50,51].map(n=>request(d,sha(String(n)),'start',JSON.stringify({name:n+'.txt',size:1}))));assert.equal(result.filter(r=>r.status===200).length,1);assert.ok(result.every(r=>[200,409,413].includes(r.status)));});
await test('wrong draft key and foreign origin rejected',async()=>{const d=await draft(),b=Buffer.from('scope');assert.equal((await request({...d,key:randomBytes(32).toString('hex')},sha(b),'start','{}')).status,404);assert.equal((await request(d,sha(b),'start','{}','',{origin:'https://foreign.invalid'})).status,403);});
await test('deleted draft cannot resume upload',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await db.query('DELETE FROM p5_estimator_work WHERE draft_id=$1',[d.id]);await db.query('DELETE FROM p5_estimator_drafts WHERE id=$1',[d.id]);assert.equal((await part(d,b)).status,404);});
await test('submitted draft cannot upload another part',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await db.query("UPDATE p5_estimator_drafts SET status='submitted' WHERE id=$1",[d.id]);assert.equal((await part(d,b)).status,409);});
await test('storage disabled preserves draft and refuses admission',async()=>{const d=await draft();process.env.P5_OBJECT_STORAGE_ENABLED='false';try{assert.equal((await request(d,sha('x'),'start','{}')).status,503);assert.equal(await count(d),0);}finally{process.env.P5_OBJECT_STORAGE_ENABLED='true';}});
await test('changed transfer size rejected',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);assert.equal((await request(d,sha(b),'start',JSON.stringify({name:'scope.txt',size:b.length+1}))).status,409);});
await test('out of range parts and truncated chunk rejected',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);for(const index of [-1,1,0.5])assert.equal((await request(d,sha(b),'part',new Uint8Array(b),'&part='+index+'&checksum='+sha(b))).status,400);assert.equal((await part(d,b.subarray(0,2),sha(b))).status,422);});
await test('chunk storage failure can retry without false receipt',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);fixture.state.failPart=true;try{assert.equal((await part(d,b)).status,503);assert.equal(await count(d),0);}finally{fixture.state.failPart=false;}assert.equal((await part(d,b)).status,200);assert.equal((await request(d,sha(b),'finish')).status,200);});
await test('final storage failure retains chunks and retries safely',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);fixture.state.failFinish=true;try{assert.equal((await request(d,sha(b),'finish')).status,503);assert.equal(await count(d),0);}finally{fixture.state.failFinish=false;}assert.equal((await request(d,sha(b),'finish')).status,200);assert.equal(await count(d),1);});
await test('corrupt saved segment rejected before receipt',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);const key=[...fixture.objects.keys()].find((k:string)=>k.includes('/'+d.id+'/'));fixture.objects.set(key,Buffer.from('wrong'));assert.equal((await request(d,sha(b),'finish')).status,503);assert.equal(await count(d),0);});
await test('retry can repair a corrupted acknowledged segment',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);const key=[...fixture.objects.keys()].find((k:string)=>k.includes('/'+d.id+'/'));fixture.objects.set(key,Buffer.from('wrong'));assert.equal((await request(d,sha(b),'finish')).status,503);assert.equal((await part(d,b)).status,200);assert.equal((await request(d,sha(b),'finish')).status,200,'retry acknowledges the original checksum without replacing corrupted stored bytes');});
await test('retry can restore a missing acknowledged segment',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);const key=[...fixture.objects.keys()].find((k:string)=>k.includes('/'+d.id+'/'));fixture.objects.delete(key);assert.equal((await request(d,sha(b),'finish')).status,503);assert.equal((await part(d,b)).status,200);assert.equal((await request(d,sha(b),'finish')).status,200,'retry does not restore a missing stored segment');});
await test('wrong whole-file digest rejected despite valid chunk checksum',async()=>{const d=await draft(),b=Buffer.from('scope'),digest=sha('different');await start(d,b,'scope.txt',digest);await part(d,b,digest);assert.equal((await request(d,digest,'finish')).status,503);assert.equal(await count(d),0);});
await test('simultaneous finish yields one durable receipt and safe replay',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);fixture.state.delay=30;try{const responses=await Promise.all([request(d,sha(b),'finish'),request(d,sha(b),'finish')]);assert.ok(responses.some(r=>r.status===200));assert.ok(responses.every(r=>[200,409].includes(r.status)));assert.equal(await count(d),1);assert.equal((await request(d,sha(b),'finish')).status,200);assert.equal(await count(d),1);}finally{fixture.state.delay=0;}});
await test('invalid PDF has no acknowledged file or orphan final object',async()=>{const d=await draft(),b=Buffer.from('not a PDF');await start(d,b,'bad.pdf');await part(d,b);assert.notEqual((await request(d,sha(b),'finish')).status,200);assert.equal(await count(d),0);const finals=[...fixture.objects.keys()].filter((k:string)=>k.includes(d.id)&&!k.startsWith('transfers/'));assert.equal(finals.length,0,'invalid file remains in final object storage without a database receipt');});
await test('damaged Office ZIP is not acknowledged as successfully uploaded',async()=>{const d=await draft(),b=Buffer.from('PKthis is not a zip');await start(d,b,'broken.xlsx');await part(d,b);assert.notEqual((await request(d,sha(b),'finish')).status,200,'signature-only Office bytes incorrectly receive success');assert.equal(await count(d),0);});
await test('malformed start JSON is a client error not transient service outage',async()=>{const d=await draft();assert.equal((await request(d,sha('x'),'start','{')).status,400);});
await test('null and array start payloads are client errors',async()=>{const d=await draft();for(const value of ['null','[]'])assert.equal((await request(d,sha('x'),'start',value)).status,400);});
await test('valid Office archive completes and preserves bytes',async()=>{const w=new ExcelJS.Workbook();w.addWorksheet('Scope').addRows([['Item','Quantity'],['Doors',4]]);const b=Buffer.from(await w.xlsx.writeBuffer()),d=await draft();await start(d,b,'scope.xlsx');await part(d,b);assert.equal((await request(d,sha(b),'finish')).status,200);assert.equal(await count(d),1);});
await test('Office archive encrypted flag rejected before final object',async()=>{const w=new ExcelJS.Workbook();w.addWorksheet('Scope').addRow(['Doors',4]);const b=Buffer.from(await w.xlsx.writeBuffer()),central=b.indexOf(Buffer.from([80,75,1,2]));assert.ok(central>=0);b.writeUInt16LE(b.readUInt16LE(central+8)|1,central+8);const d=await draft();await start(d,b,'encrypted.xlsx');await part(d,b);assert.equal((await request(d,sha(b),'finish')).status,422);assert.equal(await count(d),0);});
await test('Office archive excessive expansion rejected',async()=>{const w=new ExcelJS.Workbook();w.addWorksheet('Scope').addRow(['Doors',4]);const b=Buffer.from(await w.xlsx.writeBuffer()),central=b.indexOf(Buffer.from([80,75,1,2]));b.writeUInt32LE(17*1024*1024,central+24);const d=await draft();await start(d,b,'oversize.xlsx');await part(d,b);assert.equal((await request(d,sha(b),'finish')).status,422);});
await test('lost storage acknowledgement cleans only unreferenced final object',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);fixture.state.failAfterPersist=true;try{assert.equal((await request(d,sha(b),'finish')).status,503);assert.equal([...fixture.objects.keys()].filter((k:string)=>k.includes(d.id)&&!k.startsWith('transfers/')).length,0);assert.equal(await count(d),0);}finally{fixture.state.failAfterPersist=false;}assert.equal((await request(d,sha(b),'finish')).status,200);});
await test('source stream failure rejects even when SDK promise stays pending',async()=>{const d=await draft(),b=Buffer.from('scope'),digest=sha('wrong');await start(d,b,'scope.txt',digest);await part(d,b,digest);fixture.state.sourceErrorOnly=true;try{assert.equal((await request(d,digest,'finish')).status,503);assert.equal(await count(d),0);}finally{fixture.state.sourceErrorOnly=false;}});
await test('draft submitted during storage cannot receive a late file',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);fixture.state.beforeCommit=()=>db.query("UPDATE p5_estimator_drafts SET status='submitted' WHERE id=$1",[d.id]);try{assert.equal((await request(d,sha(b),'finish')).status,409);assert.equal(await count(d),0);assert.equal([...fixture.objects.keys()].filter((k:string)=>k.includes(d.id)&&!k.startsWith('transfers/')).length,0);}finally{fixture.state.beforeCommit=null;}});
await test('expired finalization lease cannot publish a file',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);fixture.state.beforeCommit=()=>db.query("UPDATE p5_estimator_work SET lease_until=now()-interval '1 second' WHERE draft_id=$1 AND work_key=$2",[d.id,'upload:'+sha(b)]);try{assert.equal((await request(d,sha(b),'finish')).status,409);assert.equal(await count(d),0);}finally{fixture.state.beforeCommit=null;}});
await test('failed finalization removes broken chunk from resume manifest',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);const k=[...fixture.objects.keys()].find((k:string)=>k.includes('/'+d.id+'/'));fixture.objects.delete(k);assert.equal((await request(d,sha(b),'finish')).status,503);const state=await (await request(d,sha(b),'start',JSON.stringify({name:'scope.txt',size:b.length}))).json();assert.equal(state.chunks['0'],undefined);});
await test('receipt survives a lost completion checkpoint and missing temporary chunks',async()=>{const d=await draft(),b=Buffer.from('scope');await start(d,b);await part(d,b);assert.equal((await request(d,sha(b),'finish')).status,200);await db.query("UPDATE p5_estimator_work SET payload=payload-'complete' WHERE draft_id=$1 AND work_key=$2",[d.id,'upload:'+sha(b)]);assert.equal((await request(d,sha(b),'finish')).status,200);assert.equal(await count(d),1);});
await test('valid Office archive larger than one chunk validates all metadata and bytes',async()=>{const w=new ExcelJS.Workbook();w.addWorksheet('Scope').addRows([['Item','Quantity'],['Doors',4]]);const JSZip=createRequire(path.join(root,'package.json'))('jszip'),zip=await JSZip.loadAsync(await w.xlsx.writeBuffer());zip.file('fixture-padding.bin',Buffer.alloc(scope.SCOPE_CHUNK_SIZE+200,7));const b:Buffer=await zip.generateAsync({type:'nodebuffer',compression:'STORE'}),d=await draft();assert.ok(b.length>scope.SCOPE_CHUNK_SIZE);await start(d,b,'large.xlsx');for(let at=0,n=0;at<b.length;at+=scope.SCOPE_CHUNK_SIZE,n++){const segment=b.subarray(at,at+scope.SCOPE_CHUNK_SIZE);assert.equal((await request(d,sha(b),'part',new Uint8Array(segment),'&part='+n+'&checksum='+sha(segment))).status,200);}assert.equal((await request(d,sha(b),'finish')).status,200);const bytes=await store.readUploads(d.id,d.key);assert.ok(bytes[0].data.equals(b));});
await db.database.close();
await writeFile(path.join(root,'node_modules/.cache/upload-adversarial-results.json'),JSON.stringify(rows,null,2));
console.log(JSON.stringify({passed:rows.filter(r=>r.passed).length,failed:rows.filter(r=>!r.passed).length}));
if(rows.some(r=>!r.passed))process.exitCode=1;
